/**
 * Données pour l'exercice "Le chemin des accords"
 * 300 couples de phrases avec accords dans le GN et sujet-verbe
 */

export interface AccordPhrase {
  id: number;
  level: 'B' | 'C';
  correctRow: string[]; // La phrase correcte
  incorrectRow: string[]; // La phrase incorrecte
}

export const accordPhrases: AccordPhrase[] = [
  // NIVEAU B (1-150) : Phrases simples, 5-8 mots, 1 verbe
  // 1-50: Accords sujet-verbe au présent
  { id: 1, level: 'B', correctRow: ['Le', 'musicien', 'joue', 'des', 'mélodies.'], incorrectRow: ['La', 'musicienne', 'jouent', 'une', 'mélodie.'] },
  { id: 2, level: 'B', correctRow: ['Les', 'chats', 'adorent', 'les', 'croquettes.'], incorrectRow: ['Les', 'chat', 'adore', 'les', 'croquette.'] },
  { id: 3, level: 'B', correctRow: ['Les', 'enfants', 'cherchent', 'son', 'stylo.'], incorrectRow: ['La', 'fillette', 'cherchent', 'leurs', 'crayon.'] },
  { id: 4, level: 'B', correctRow: ['Mes', 'amis', 'partent', 'chez', 'leurs', 'cousins.'], incorrectRow: ['Mes', 'amis', 'parte', 'chez', 'leurs', 'cousin.'] },
  { id: 5, level: 'B', correctRow: ['La', 'petite', 'fille', 'mange', 'une', 'pomme.'], incorrectRow: ['Les', 'petit', 'filles', 'mange', 'un', 'pommes.'] },
  { id: 6, level: 'B', correctRow: ['Les', 'oiseaux', 'chantent', 'dans', 'les', 'arbres.'], incorrectRow: ['Le', 'oiseau', 'chante', 'dans', 'le', 'arbre.'] },
  { id: 7, level: 'B', correctRow: ['Mon', 'chien', 'aboie', 'contre', 'le', 'facteur.'], incorrectRow: ['Mes', 'chiens', 'aboie', 'contre', 'les', 'facteur.'] },
  { id: 8, level: 'B', correctRow: ['Les', 'élèves', 'écoutent', 'la', 'maîtresse.'], incorrectRow: ['Le', 'élève', 'écoute', 'les', 'maîtresses.'] },
  { id: 9, level: 'B', correctRow: ['Ta', 'sœur', 'dessine', 'un', 'beau', 'château.'], incorrectRow: ['Tes', 'sœurs', 'dessine', 'des', 'beaux', 'château.'] },
  { id: 10, level: 'B', correctRow: ['Les', 'fleurs', 'poussent', 'dans', 'le', 'jardin.'], incorrectRow: ['La', 'fleur', 'pousse', 'dans', 'les', 'jardins.'] },
  { id: 11, level: 'B', correctRow: ['Notre', 'professeur', 'explique', 'la', 'leçon.'], incorrectRow: ['Nos', 'professeurs', 'explique', 'les', 'leçon.'] },
  { id: 12, level: 'B', correctRow: ['Les', 'voitures', 'roulent', 'sur', "l'autoroute."], incorrectRow: ['La', 'voiture', 'roule', 'sur', 'les', 'autoroutes.'] },
  { id: 13, level: 'B', correctRow: ['Ton', 'frère', 'construit', 'une', 'cabane.'], incorrectRow: ['Tes', 'frères', 'construit', 'des', 'cabane.'] },
  { id: 14, level: 'B', correctRow: ['Les', 'abeilles', 'butinent', 'les', 'fleurs.'], incorrectRow: ['Le', 'abeille', 'butine', 'la', 'fleur.'] },
  { id: 15, level: 'B', correctRow: ['Ma', 'mère', 'prépare', 'le', 'repas.'], incorrectRow: ['Mes', 'mères', 'prépare', 'les', 'repas.'] },
  { id: 16, level: 'B', correctRow: ['Les', 'pirates', 'cherchent', 'un', 'trésor.'], incorrectRow: ['Le', 'pirate', 'cherche', 'des', 'trésors.'] },
  { id: 17, level: 'B', correctRow: ['Sa', 'cousine', 'joue', 'du', 'piano.'], incorrectRow: ['Ses', 'cousines', 'joue', 'de', 'la', 'pianos.'] },
  { id: 18, level: 'B', correctRow: ['Les', 'poissons', 'nagent', 'dans', "l'aquarium."], incorrectRow: ['Le', 'poisson', 'nage', 'dans', 'les', 'aquariums.'] },
  { id: 19, level: 'B', correctRow: ['Leur', 'père', 'répare', 'la', 'voiture.'], incorrectRow: ['Leurs', 'pères', 'répare', 'les', 'voiture.'] },
  { id: 20, level: 'B', correctRow: ['Les', 'lions', 'rugissent', 'dans', 'la', 'savane.'], incorrectRow: ['Le', 'lion', 'rugit', 'dans', 'les', 'savanes.'] },
  { id: 21, level: 'B', correctRow: ['Cette', 'dame', 'travaille', 'à', "l'hôpital."], incorrectRow: ['Ces', 'dames', 'travaille', 'aux', 'hôpitaux.'] },
  { id: 22, level: 'B', correctRow: ['Les', 'papillons', 'volent', 'dans', 'le', 'ciel.'], incorrectRow: ['Le', 'papillon', 'vole', 'dans', 'les', 'ciels.'] },
  { id: 23, level: 'B', correctRow: ['Mon', 'voisin', 'tond', 'sa', 'pelouse.'], incorrectRow: ['Mes', 'voisins', 'tond', 'ses', 'pelouse.'] },
  { id: 24, level: 'B', correctRow: ['Les', 'bébés', 'dorment', 'dans', 'leur', 'lit.'], incorrectRow: ['Le', 'bébé', 'dors', 'dans', 'leurs', 'lits.'] },
  { id: 25, level: 'B', correctRow: ['Votre', 'chat', 'grimpe', 'aux', 'arbres.'], incorrectRow: ['Vos', 'chats', 'grimpe', 'au', 'arbre.'] },
  { id: 26, level: 'B', correctRow: ['Les', 'dragons', 'crachent', 'du', 'feu.'], incorrectRow: ['Le', 'dragon', 'crache', 'des', 'feux.'] },
  { id: 27, level: 'B', correctRow: ['Son', 'ami', 'collectionne', 'les', 'timbres.'], incorrectRow: ['Ses', 'amis', 'collectionne', 'le', 'timbre.'] },
  { id: 28, level: 'B', correctRow: ['Les', 'dauphins', 'sautent', 'hors', 'de', "l'eau."], incorrectRow: ['Le', 'dauphin', 'saute', 'hors', 'des', 'eaux.'] },
  { id: 29, level: 'B', correctRow: ['Cette', 'chanteuse', 'interprète', 'une', 'chanson.'], incorrectRow: ['Ces', 'chanteuses', 'interprète', 'des', 'chanson.'] },
  { id: 30, level: 'B', correctRow: ['Les', 'clowns', 'amusent', 'les', 'enfants.'], incorrectRow: ['Le', 'clown', 'amuse', 'le', 'enfant.'] },
  { id: 31, level: 'B', correctRow: ['Leur', 'grand-mère', 'tricote', 'une', 'écharpe.'], incorrectRow: ['Leurs', 'grand-mères', 'tricote', 'des', 'écharpe.'] },
  { id: 32, level: 'B', correctRow: ['Les', 'pingouins', 'marchent', 'sur', 'la', 'glace.'], incorrectRow: ['Le', 'pingouin', 'marche', 'sur', 'les', 'glaces.'] },
  { id: 33, level: 'B', correctRow: ['Ma', 'copine', 'lit', 'un', 'livre', 'passionnant.'], incorrectRow: ['Mes', 'copines', 'lit', 'des', 'livre', 'passionnant.'] },
  { id: 34, level: 'B', correctRow: ['Les', 'loups', 'hurlent', 'à', 'la', 'lune.'], incorrectRow: ['Le', 'loup', 'hurle', 'aux', 'lunes.'] },
  { id: 35, level: 'B', correctRow: ['Ton', 'oncle', 'conduit', 'un', 'camion.'], incorrectRow: ['Tes', 'oncles', 'conduit', 'des', 'camion.'] },
  { id: 36, level: 'B', correctRow: ['Les', 'sorcières', 'préparent', 'une', 'potion.'], incorrectRow: ['La', 'sorcière', 'prépare', 'des', 'potions.'] },
  { id: 37, level: 'B', correctRow: ['Notre', 'équipe', 'remporte', 'le', 'match.'], incorrectRow: ['Nos', 'équipes', 'remporte', 'les', 'matchs.'] },
  { id: 38, level: 'B', correctRow: ['Les', 'tortues', 'avancent', 'très', 'lentement.'], incorrectRow: ['La', 'tortue', 'avance', 'très', 'lentement.'] },
  { id: 39, level: 'B', correctRow: ['Sa', 'tante', 'cuisine', 'des', 'crêpes.'], incorrectRow: ['Ses', 'tantes', 'cuisine', 'de', 'la', 'crêpe.'] },
  { id: 40, level: 'B', correctRow: ['Les', 'étoiles', 'brillent', 'la', 'nuit.'], incorrectRow: ['Le', 'étoile', 'brille', 'les', 'nuits.'] },
  { id: 41, level: 'B', correctRow: ['Mon', 'cousin', 'adore', 'le', 'chocolat.'], incorrectRow: ['Mes', 'cousins', 'adore', 'les', 'chocolat.'] },
  { id: 42, level: 'B', correctRow: ['Les', 'chevaux', 'galopent', 'dans', 'le', 'pré.'], incorrectRow: ['Le', 'cheval', 'galope', 'dans', 'les', 'prés.'] },
  { id: 43, level: 'B', correctRow: ['Votre', 'fille', 'apprend', 'ses', 'leçons.'], incorrectRow: ['Vos', 'filles', 'apprend', 'son', 'leçon.'] },
  { id: 44, level: 'B', correctRow: ['Les', 'robots', 'obéissent', 'aux', 'ordres.'], incorrectRow: ['Le', 'robot', 'obéit', 'à', "l'ordre."] },
  { id: 45, level: 'B', correctRow: ['Leur', 'ami', 'raconte', 'une', 'histoire.'], incorrectRow: ['Leurs', 'amis', 'raconte', 'des', 'histoire.'] },
  { id: 46, level: 'B', correctRow: ['Les', 'fourmis', 'transportent', 'des', 'miettes.'], incorrectRow: ['La', 'fourmi', 'transporte', 'de', 'la', 'miette.'] },
  { id: 47, level: 'B', correctRow: ['Cette', 'histoire', 'plaît', 'aux', 'enfants.'], incorrectRow: ['Ces', 'histoires', 'plaît', 'au', 'enfant.'] },
  { id: 48, level: 'B', correctRow: ['Les', 'baleines', 'plongent', 'dans', "l'océan."], incorrectRow: ['La', 'baleine', 'plonge', 'dans', 'les', 'océans.'] },
  { id: 49, level: 'B', correctRow: ['Ton', 'camarade', 'range', 'ses', 'affaires.'], incorrectRow: ['Tes', 'camarades', 'range', 'son', 'affaire.'] },
  { id: 50, level: 'B', correctRow: ['Les', 'grenouilles', 'coassent', 'près', 'de', "l'étang."], incorrectRow: ['La', 'grenouille', 'coasse', 'près', 'des', 'étangs.'] },

  // 51-100: Accords dans le GN (adjectifs, déterminants)
  { id: 51, level: 'B', correctRow: ['Les', 'grandes', 'maisons', 'sont', 'blanches.'], incorrectRow: ['Le', 'grand', 'maison', 'est', 'blanche.'] },
  { id: 52, level: 'B', correctRow: ['Un', 'petit', 'garçon', 'court', 'vite.'], incorrectRow: ['Des', 'petits', 'garçons', 'court', 'vite.'] },
  { id: 53, level: 'B', correctRow: ['Mes', 'nouvelles', 'chaussures', 'sont', 'rouges.'], incorrectRow: ['Ma', 'nouvelle', 'chaussure', 'est', 'rouge.'] },
  { id: 54, level: 'B', correctRow: ['Les', 'gentils', 'animaux', 'mangent', "l'herbe."], incorrectRow: ['Le', 'gentil', 'animal', 'mange', 'les', 'herbes.'] },
  { id: 55, level: 'B', correctRow: ['Une', 'jolie', 'fleur', 'pousse', 'ici.'], incorrectRow: ['Des', 'jolies', 'fleurs', 'pousse', 'ici.'] },
  { id: 56, level: 'B', correctRow: ['Les', 'vieux', 'livres', 'restent', 'fermés.'], incorrectRow: ['Le', 'vieil', 'livre', 'reste', 'fermé.'] },
  { id: 57, level: 'B', correctRow: ['Ton', 'meilleur', 'ami', 'arrive', 'demain.'], incorrectRow: ['Tes', 'meilleurs', 'amis', 'arrive', 'demain.'] },
  { id: 58, level: 'B', correctRow: ['Les', 'hautes', 'montagnes', 'touchent', 'le', 'ciel.'], incorrectRow: ['La', 'haute', 'montagne', 'touche', 'les', 'ciels.'] },
  { id: 59, level: 'B', correctRow: ['Ma', 'petite', 'sœur', 'pleure', 'souvent.'], incorrectRow: ['Mes', 'petites', 'sœurs', 'pleure', 'souvent.'] },
  { id: 60, level: 'B', correctRow: ['Les', 'beaux', 'jardins', 'fleurissent', 'au', 'printemps.'], incorrectRow: ['Le', 'beau', 'jardin', 'fleurit', 'aux', 'printemps.'] },
  { id: 61, level: 'B', correctRow: ['Un', 'gros', 'nuage', 'cache', 'le', 'soleil.'], incorrectRow: ['Des', 'gros', 'nuages', 'cache', 'les', 'soleils.'] },
  { id: 62, level: 'B', correctRow: ['Les', 'longs', 'cheveux', 'brillent', 'au', 'soleil.'], incorrectRow: ['Le', 'long', 'cheveu', 'brille', 'aux', 'soleils.'] },
  { id: 63, level: 'B', correctRow: ['Votre', 'nouveau', 'vélo', 'roule', 'bien.'], incorrectRow: ['Vos', 'nouveaux', 'vélos', 'roule', 'bien.'] },
  { id: 64, level: 'B', correctRow: ['Les', 'jeunes', 'filles', 'dansent', 'ensemble.'], incorrectRow: ['La', 'jeune', 'fille', 'danse', 'ensemble.'] },
  { id: 65, level: 'B', correctRow: ['Son', 'grand', 'frère', 'joue', 'dehors.'], incorrectRow: ['Ses', 'grands', 'frères', 'joue', 'dehors.'] },
  { id: 66, level: 'B', correctRow: ['Les', 'belles', 'histoires', 'finissent', 'bien.'], incorrectRow: ['La', 'belle', 'histoire', 'finis', 'bien.'] },
  { id: 67, level: 'B', correctRow: ['Leur', 'vieille', 'voiture', 'démarre', 'mal.'], incorrectRow: ['Leurs', 'vieilles', 'voitures', 'démarre', 'mal.'] },
  { id: 68, level: 'B', correctRow: ['Les', 'bonnes', 'notes', 'réjouissent', 'les', 'parents.'], incorrectRow: ['La', 'bonne', 'note', 'réjouit', 'le', 'parent.'] },
  { id: 69, level: 'B', correctRow: ['Cette', 'grande', 'tour', 'domine', 'la', 'ville.'], incorrectRow: ['Ces', 'grandes', 'tours', 'domine', 'les', 'villes.'] },
  { id: 70, level: 'B', correctRow: ['Les', 'petites', 'souris', 'grignotent', 'le', 'fromage.'], incorrectRow: ['La', 'petite', 'souris', 'grignote', 'les', 'fromages.'] },
  { id: 71, level: 'B', correctRow: ['Mon', 'cher', 'papa', 'travaille', 'beaucoup.'], incorrectRow: ['Mes', 'chers', 'papas', 'travaille', 'beaucoup.'] },
  { id: 72, level: 'B', correctRow: ['Les', 'fortes', 'pluies', 'inondent', 'les', 'rues.'], incorrectRow: ['La', 'forte', 'pluie', 'inonde', 'la', 'rue.'] },
  { id: 73, level: 'B', correctRow: ['Ta', 'jolie', 'robe', 'brille', 'magnifiquement.'], incorrectRow: ['Tes', 'jolies', 'robes', 'brille', 'magnifiquement.'] },
  { id: 74, level: 'B', correctRow: ['Les', 'derniers', 'jours', 'passent', 'rapidement.'], incorrectRow: ['Le', 'dernier', 'jour', 'passe', 'rapidement.'] },
  { id: 75, level: 'B', correctRow: ['Notre', 'cher', 'ami', 'part', 'en', 'voyage.'], incorrectRow: ['Nos', 'chers', 'amis', 'part', 'en', 'voyages.'] },
  { id: 76, level: 'B', correctRow: ['Les', 'premiers', 'fruits', 'mûrissent', 'en', 'été.'], incorrectRow: ['Le', 'premier', 'fruit', 'mûrit', 'en', 'étés.'] },
  { id: 77, level: 'B', correctRow: ['Sa', 'douce', 'voix', 'charme', "l'audience."], incorrectRow: ['Ses', 'douces', 'voix', 'charme', 'les', 'audiences.'] },
  { id: 78, level: 'B', correctRow: ['Les', 'mauvaises', 'herbes', 'envahissent', 'le', 'jardin.'], incorrectRow: ['La', 'mauvaise', 'herbe', 'envahit', 'les', 'jardins.'] },
  { id: 79, level: 'B', correctRow: ['Ton', 'fidèle', 'compagnon', 'reste', 'près', 'de', 'toi.'], incorrectRow: ['Tes', 'fidèles', 'compagnons', 'reste', 'près', 'de', 'toi.'] },
  { id: 80, level: 'B', correctRow: ['Les', 'brillantes', 'étoiles', 'scintillent', 'toujours.'], incorrectRow: ['La', 'brillante', 'étoile', 'scintille', 'toujours.'] },
  { id: 81, level: 'B', correctRow: ['Mon', 'brave', 'chien', 'défend', 'la', 'maison.'], incorrectRow: ['Mes', 'braves', 'chiens', 'défend', 'les', 'maisons.'] },
  { id: 82, level: 'B', correctRow: ['Les', 'froids', 'hivers', 'glacent', 'les', 'lacs.'], incorrectRow: ['Le', 'froid', 'hiver', 'glace', 'le', 'lac.'] },
  { id: 83, level: 'B', correctRow: ['Votre', 'sage', 'décision', 'plaît', 'à', 'tous.'], incorrectRow: ['Vos', 'sages', 'décisions', 'plaît', 'à', 'tous.'] },
  { id: 84, level: 'B', correctRow: ['Les', 'drôles', 'de', 'clowns', 'font', 'rire.'], incorrectRow: ['Le', 'drôle', 'de', 'clown', 'fait', 'rire.'] },
  { id: 85, level: 'B', correctRow: ['Leur', 'importante', 'réunion', 'commence', 'bientôt.'], incorrectRow: ['Leurs', 'importantes', 'réunions', 'commence', 'bientôt.'] },
  { id: 86, level: 'B', correctRow: ['Les', 'légères', 'plumes', 'volent', 'au', 'vent.'], incorrectRow: ['La', 'légère', 'plume', 'vole', 'aux', 'vents.'] },
  { id: 87, level: 'B', correctRow: ['Cette', 'étrange', 'créature', 'apparaît', 'la', 'nuit.'], incorrectRow: ['Ces', 'étranges', 'créatures', 'apparaît', 'les', 'nuits.'] },
  { id: 88, level: 'B', correctRow: ['Les', 'plates', 'surfaces', 'réfléchissent', 'la', 'lumière.'], incorrectRow: ['La', 'plate', 'surface', 'réfléchit', 'les', 'lumières.'] },
  { id: 89, level: 'B', correctRow: ['Ton', 'seul', 'espoir', 'reste', 'vivant.'], incorrectRow: ['Tes', 'seuls', 'espoirs', 'reste', 'vivant.'] },
  { id: 90, level: 'B', correctRow: ['Les', 'verts', 'pâturages', 'nourrissent', 'les', 'vaches.'], incorrectRow: ['Le', 'vert', 'pâturage', 'nourrit', 'la', 'vache.'] },
  { id: 91, level: 'B', correctRow: ['Ma', 'préférée', 'chanson', 'passe', 'souvent.'], incorrectRow: ['Mes', 'préférées', 'chansons', 'passe', 'souvent.'] },
  { id: 92, level: 'B', correctRow: ['Les', 'lourds', 'colis', 'arrivent', 'demain.'], incorrectRow: ['Le', 'lourd', 'colis', 'arrive', 'demain.'] },
  { id: 93, level: 'B', correctRow: ['Son', 'unique', 'talent', 'impressionne', 'tout', 'le', 'monde.'], incorrectRow: ['Ses', 'uniques', 'talents', 'impressionne', 'tout', 'le', 'monde.'] },
  { id: 94, level: 'B', correctRow: ['Les', 'courts', 'chemins', 'mènent', 'au', 'village.'], incorrectRow: ['Le', 'court', 'chemin', 'mène', 'aux', 'villages.'] },
  { id: 95, level: 'B', correctRow: ['Leur', 'prochaine', 'aventure', 'commence', 'ici.'], incorrectRow: ['Leurs', 'prochaines', 'aventures', 'commence', 'ici.'] },
  { id: 96, level: 'B', correctRow: ['Les', 'rapides', 'coureurs', 'gagnent', 'la', 'course.'], incorrectRow: ['Le', 'rapide', 'coureur', 'gagne', 'les', 'courses.'] },
  { id: 97, level: 'B', correctRow: ['Notre', 'ancienne', 'école', 'ferme', 'ses', 'portes.'], incorrectRow: ['Nos', 'anciennes', 'écoles', 'ferme', 'son', 'porte.'] },
  { id: 98, level: 'B', correctRow: ['Les', 'molles', 'couvertures', 'réchauffent', 'les', 'enfants.'], incorrectRow: ['La', 'molle', 'couverture', 'réchauffe', 'le', 'enfant.'] },
  { id: 99, level: 'B', correctRow: ['Sa', 'vraie', 'nature', 'apparaît', 'enfin.'], incorrectRow: ['Ses', 'vraies', 'natures', 'apparaît', 'enfin.'] },
  { id: 100, level: 'B', correctRow: ['Les', 'dures', 'épreuves', 'renforcent', 'le', 'caractère.'], incorrectRow: ['La', 'dure', 'épreuve', 'renforce', 'les', 'caractères.'] },

  // 101-150: Mélange accords GN + sujet-verbe
  { id: 101, level: 'B', correctRow: ['Les', 'petits', 'oiseaux', 'chantent', 'doucement.'], incorrectRow: ['Le', 'petit', 'oiseau', 'chante', 'doucement.'] },
  { id: 102, level: 'B', correctRow: ['Ma', 'grande', 'sœur', 'étudie', 'beaucoup.'], incorrectRow: ['Mes', 'grandes', 'sœurs', 'étudie', 'beaucoup.'] },
  { id: 103, level: 'B', correctRow: ['Les', 'gentilles', 'dames', 'aident', 'les', 'pauvres.'], incorrectRow: ['La', 'gentille', 'dame', 'aide', 'le', 'pauvre.'] },
  { id: 104, level: 'B', correctRow: ['Ton', 'nouveau', 'jouet', 'fonctionne', 'bien.'], incorrectRow: ['Tes', 'nouveaux', 'jouets', 'fonctionne', 'bien.'] },
  { id: 105, level: 'B', correctRow: ['Les', 'hauts', 'immeubles', 'dominent', 'la', 'ville.'], incorrectRow: ['Le', 'haut', 'immeuble', 'domine', 'les', 'villes.'] },
  { id: 106, level: 'B', correctRow: ['Votre', 'jeune', 'enfant', 'grandit', 'vite.'], incorrectRow: ['Vos', 'jeunes', 'enfants', 'grandit', 'vite.'] },
  { id: 107, level: 'B', correctRow: ['Les', 'bons', 'élèves', 'réussissent', 'toujours.'], incorrectRow: ['Le', 'bon', 'élève', 'réussit', 'toujours.'] },
  { id: 108, level: 'B', correctRow: ['Leur', 'vieille', 'maison', 'tombe', 'en', 'ruine.'], incorrectRow: ['Leurs', 'vieilles', 'maisons', 'tombe', 'en', 'ruines.'] },
  { id: 109, level: 'B', correctRow: ['Les', 'rares', 'moments', 'passent', 'trop', 'vite.'], incorrectRow: ['Le', 'rare', 'moment', 'passe', 'trop', 'vite.'] },
  { id: 110, level: 'B', correctRow: ['Cette', 'belle', 'journée', 'finit', 'bien.'], incorrectRow: ['Ces', 'belles', 'journées', 'finit', 'bien.'] },
  { id: 111, level: 'B', correctRow: ['Les', 'fous', 'rires', 'éclatent', 'partout.'], incorrectRow: ['Le', 'fou', 'rire', 'éclate', 'partout.'] },
  { id: 112, level: 'B', correctRow: ['Son', 'long', 'voyage', 'commence', 'maintenant.'], incorrectRow: ['Ses', 'longs', 'voyages', 'commence', 'maintenant.'] },
  { id: 113, level: 'B', correctRow: ['Les', 'profondes', 'mers', 'cachent', 'des', 'secrets.'], incorrectRow: ['La', 'profonde', 'mer', 'cache', 'de', 'secret.'] },
  { id: 114, level: 'B', correctRow: ['Mon', 'cher', 'ami', 'arrive', 'demain.'], incorrectRow: ['Mes', 'chers', 'amis', 'arrive', 'demain.'] },
  { id: 115, level: 'B', correctRow: ['Les', 'douces', 'mélodies', 'bercent', 'les', 'bébés.'], incorrectRow: ['La', 'douce', 'mélodie', 'berce', 'le', 'bébé.'] },
  { id: 116, level: 'B', correctRow: ['Ta', 'seule', 'chance', 'reste', 'intacte.'], incorrectRow: ['Tes', 'seules', 'chances', 'reste', 'intacte.'] },
  { id: 117, level: 'B', correctRow: ['Les', 'forts', 'vents', 'secouent', 'les', 'arbres.'], incorrectRow: ['Le', 'fort', 'vent', 'secoue', "l'arbre."] },
  { id: 118, level: 'B', correctRow: ['Notre', 'petite', 'chatte', 'dort', 'tranquillement.'], incorrectRow: ['Nos', 'petites', 'chattes', 'dort', 'tranquillement.'] },
  { id: 119, level: 'B', correctRow: ['Les', 'sombres', 'forêts', 'abritent', 'des', 'animaux.'], incorrectRow: ['La', 'sombre', 'forêt', 'abrite', 'un', 'animal.'] },
  { id: 120, level: 'B', correctRow: ['Sa', 'dernière', 'tentative', 'réussit', 'enfin.'], incorrectRow: ['Ses', 'dernières', 'tentatives', 'réussit', 'enfin.'] },
  { id: 121, level: 'B', correctRow: ['Les', 'gros', 'camions', 'transportent', 'des', 'marchandises.'], incorrectRow: ['Le', 'gros', 'camion', 'transporte', 'de', 'la', 'marchandise.'] },
  { id: 122, level: 'B', correctRow: ['Leur', 'nouvelle', 'idée', 'plaît', 'beaucoup.'], incorrectRow: ['Leurs', 'nouvelles', 'idées', 'plaît', 'beaucoup.'] },
  { id: 123, level: 'B', correctRow: ['Les', 'fraîches', 'salades', 'accompagnent', 'le', 'repas.'], incorrectRow: ['La', 'fraîche', 'salade', 'accompagne', 'les', 'repas.'] },
  { id: 124, level: 'B', correctRow: ['Mon', 'vieux', 'pull', 'tient', 'chaud.'], incorrectRow: ['Mes', 'vieux', 'pulls', 'tient', 'chaud.'] },
  { id: 125, level: 'B', correctRow: ['Les', 'premières', 'neiges', 'tombent', 'en', 'novembre.'], incorrectRow: ['La', 'première', 'neige', 'tombe', 'en', 'novembres.'] },
  { id: 126, level: 'B', correctRow: ['Votre', 'meilleure', 'amie', 'reste', 'fidèle.'], incorrectRow: ['Vos', 'meilleures', 'amies', 'reste', 'fidèle.'] },
  { id: 127, level: 'B', correctRow: ['Les', 'larges', 'fenêtres', 'laissent', 'entrer', 'la', 'lumière.'], incorrectRow: ['La', 'large', 'fenêtre', 'laisse', 'entrer', 'les', 'lumières.'] },
  { id: 128, level: 'B', correctRow: ['Cette', 'simple', 'question', 'demande', 'réflexion.'], incorrectRow: ['Ces', 'simples', 'questions', 'demande', 'réflexion.'] },
  { id: 129, level: 'B', correctRow: ['Les', 'pâles', 'couleurs', 'apaisent', "l'esprit."], incorrectRow: ['La', 'pâle', 'couleur', 'apaise', 'les', 'esprits.'] },
  { id: 130, level: 'B', correctRow: ['Son', 'important', 'discours', 'marque', 'les', 'esprits.'], incorrectRow: ['Ses', 'importants', 'discours', 'marque', "l'esprit."] },
  { id: 131, level: 'B', correctRow: ['Les', 'doux', 'parfums', 'embaument', "l'air."], incorrectRow: ['Le', 'doux', 'parfum', 'embaume', 'les', 'airs.'] },
  { id: 132, level: 'B', correctRow: ['Ma', 'chère', 'maman', 'prépare', 'le', 'dîner.'], incorrectRow: ['Mes', 'chères', 'mamans', 'prépare', 'les', 'dîners.'] },
  { id: 133, level: 'B', correctRow: ['Les', 'braves', 'soldats', 'défendent', 'le', 'pays.'], incorrectRow: ['Le', 'brave', 'soldat', 'défend', 'les', 'pays.'] },
  { id: 134, level: 'B', correctRow: ['Ton', 'étrange', 'comportement', 'inquiète', 'tout', 'le', 'monde.'], incorrectRow: ['Tes', 'étranges', 'comportements', 'inquiète', 'tout', 'le', 'monde.'] },
  { id: 135, level: 'B', correctRow: ['Les', 'plates', 'régions', 'favorisent', "l'agriculture."], incorrectRow: ['La', 'plate', 'région', 'favorise', 'les', 'agricultures.'] },
  { id: 136, level: 'B', correctRow: ['Leur', 'unique', 'fille', 'part', 'étudier.'], incorrectRow: ['Leurs', 'uniques', 'filles', 'part', 'étudier.'] },
  { id: 137, level: 'B', correctRow: ['Les', 'sages', 'conseils', 'guident', 'nos', 'choix.'], incorrectRow: ['Le', 'sage', 'conseil', 'guide', 'notre', 'choix.'] },
  { id: 138, level: 'B', correctRow: ['Notre', 'commune', 'passion', 'nous', 'unit.'], incorrectRow: ['Nos', 'communes', 'passions', 'nous', 'unit.'] },
  { id: 139, level: 'B', correctRow: ['Les', 'drôles', "d'oiseaux", 'volent', 'à', "l'envers."], incorrectRow: ['Le', 'drôle', "d'oiseau", 'vole', 'à', "l'envers."] },
  { id: 140, level: 'B', correctRow: ['Sa', 'fausse', 'excuse', 'trompe', 'personne.'], incorrectRow: ['Ses', 'fausses', 'excuses', 'trompe', 'personne.'] },
  { id: 141, level: 'B', correctRow: ['Les', 'légères', 'brises', 'rafraîchissent', "l'atmosphère."], incorrectRow: ['La', 'légère', 'brise', 'rafraîchit', 'les', 'atmosphères.'] },
  { id: 142, level: 'B', correctRow: ['Mon', 'fidèle', 'compagnon', 'reste', 'toujours', 'là.'], incorrectRow: ['Mes', 'fidèles', 'compagnons', 'reste', 'toujours', 'là.'] },
  { id: 143, level: 'B', correctRow: ['Les', 'basses', 'températures', 'gèlent', "l'eau."], incorrectRow: ['La', 'basse', 'température', 'gèle', 'les', 'eaux.'] },
  { id: 144, level: 'B', correctRow: ['Votre', 'prochaine', 'visite', 'nous', 'réjouit.'], incorrectRow: ['Vos', 'prochaines', 'visites', 'nous', 'réjouit.'] },
  { id: 145, level: 'B', correctRow: ['Les', 'fines', 'herbes', 'parfument', 'les', 'plats.'], incorrectRow: ['La', 'fine', 'herbe', 'parfume', 'le', 'plat.'] },
  { id: 146, level: 'B', correctRow: ['Cette', 'lointaine', 'époque', 'fascine', 'les', 'historiens.'], incorrectRow: ['Ces', 'lointaines', 'époques', 'fascine', "l'historien."] },
  { id: 147, level: 'B', correctRow: ['Les', 'denses', 'forêts', 'protègent', 'la', 'faune.'], incorrectRow: ['La', 'dense', 'forêt', 'protège', 'les', 'faunes.'] },
  { id: 148, level: 'B', correctRow: ['Ton', 'prochain', 'anniversaire', 'arrive', 'bientôt.'], incorrectRow: ['Tes', 'prochains', 'anniversaires', 'arrive', 'bientôt.'] },
  { id: 149, level: 'B', correctRow: ['Les', 'chaudes', 'journées', 'fatiguent', 'tout', 'le', 'monde.'], incorrectRow: ['La', 'chaude', 'journée', 'fatigue', 'tout', 'le', 'monde.'] },
  { id: 150, level: 'B', correctRow: ['Leur', 'grande', 'maison', 'accueille', 'beaucoup', "d'invités."], incorrectRow: ['Leurs', 'grandes', 'maisons', 'accueille', 'beaucoup', "d'invité."] },

  // NIVEAU C (151-300) : Phrases complexes, 8-12 mots, 2 verbes
  // 151-200: Phrases avec propositions relatives
  { id: 151, level: 'C', correctRow: ['Les', 'enfants', 'qui', 'jouent', 'dehors', 'rentrent', 'à', 'cinq', 'heures.'], incorrectRow: ['Le', 'enfant', 'qui', 'joue', 'dehors', 'rentre', 'à', 'cinq', 'heure.'] },
  { id: 152, level: 'C', correctRow: ['Ma', 'sœur', 'qui', 'habite', 'Paris', 'viendra', 'nous', 'voir', 'demain.'], incorrectRow: ['Mes', 'sœurs', 'qui', 'habite', 'Paris', 'viendra', 'nous', 'voir', 'demain.'] },
  { id: 153, level: 'C', correctRow: ['Les', 'oiseaux', 'qui', 'chantent', 'le', 'matin', 'réveillent', 'tout', 'le', 'quartier.'], incorrectRow: ['Le', 'oiseau', 'qui', 'chante', 'le', 'matin', 'réveille', 'tout', 'le', 'quartier.'] },
  { id: 154, level: 'C', correctRow: ['Le', 'chat', 'qui', 'dort', 'sur', 'le', 'canapé', 'appartient', 'à', 'mon', 'voisin.'], incorrectRow: ['Les', 'chats', 'qui', 'dort', 'sur', 'le', 'canapé', 'appartient', 'à', 'mon', 'voisin.'] },
  { id: 155, level: 'C', correctRow: ['Les', 'élèves', 'qui', 'travaillent', 'bien', 'réussissent', 'leurs', 'examens.'], incorrectRow: ['Le', 'élève', 'qui', 'travaille', 'bien', 'réussit', 'leur', 'examen.'] },
  { id: 156, level: 'C', correctRow: ['Mon', 'frère', 'qui', 'aime', 'le', 'sport', 'joue', 'au', 'football', 'chaque', 'samedi.'], incorrectRow: ['Mes', 'frères', 'qui', 'aime', 'le', 'sport', 'joue', 'au', 'football', 'chaque', 'samedi.'] },
  { id: 157, level: 'C', correctRow: ['Les', 'fleurs', 'qui', 'poussent', 'ici', 'embaument', 'tout', 'le', 'jardin.'], incorrectRow: ['La', 'fleur', 'qui', 'pousse', 'ici', 'embaume', 'tout', 'le', 'jardin.'] },
  { id: 158, level: 'C', correctRow: ['La', 'dame', 'qui', 'vend', 'des', 'fleurs', 'sourit', 'toujours', 'gentiment.'], incorrectRow: ['Les', 'dames', 'qui', 'vend', 'des', 'fleur', 'sourit', 'toujours', 'gentiment.'] },
  { id: 159, level: 'C', correctRow: ['Les', 'livres', 'qui', 'racontent', 'des', 'aventures', 'passionnent', 'les', 'jeunes.'], incorrectRow: ['Le', 'livre', 'qui', 'raconte', 'des', 'aventure', 'passionne', 'le', 'jeune.'] },
  { id: 160, level: 'C', correctRow: ['Mon', 'ami', 'qui', 'collectionne', 'les', 'timbres', 'possède', 'des', 'pièces', 'rares.'], incorrectRow: ['Mes', 'amis', 'qui', 'collectionne', 'le', 'timbre', 'possède', 'de', 'la', 'pièce', 'rare.'] },
  { id: 161, level: 'C', correctRow: ['Les', 'nuages', 'qui', 'arrivent', 'du', 'nord', 'annoncent', 'la', 'pluie.'], incorrectRow: ['Le', 'nuage', 'qui', 'arrive', 'du', 'nord', 'annonce', 'les', 'pluies.'] },
  { id: 162, level: 'C', correctRow: ['La', 'voiture', 'qui', 'roule', 'trop', 'vite', 'risque', "l'accident."], incorrectRow: ['Les', 'voitures', 'qui', 'roule', 'trop', 'vite', 'risque', 'les', 'accidents.'] },
  { id: 163, level: 'C', correctRow: ['Les', 'histoires', 'qui', 'finissent', 'bien', 'plaisent', 'aux', 'enfants.'], incorrectRow: ['Le', 'histoire', 'qui', 'finis', 'bien', 'plaît', 'à', "l'enfant."] },
  { id: 164, level: 'C', correctRow: ['Mon', 'cousin', 'qui', 'étudie', 'la', 'médecine', 'deviendra', 'bientôt', 'docteur.'], incorrectRow: ['Mes', 'cousins', 'qui', 'étudie', 'la', 'médecine', 'deviendra', 'bientôt', 'docteurs.'] },
  { id: 165, level: 'C', correctRow: ['Les', 'chiens', 'qui', 'aboient', 'fort', 'effraient', 'les', 'passants.'], incorrectRow: ['Le', 'chien', 'qui', 'aboie', 'fort', 'effraie', 'le', 'passant.'] },
  { id: 166, level: 'C', correctRow: ['La', 'fillette', 'qui', 'porte', 'une', 'robe', 'rouge', 'danse', 'gracieusement.'], incorrectRow: ['Les', 'fillettes', 'qui', 'porte', 'des', 'robe', 'rouge', 'danse', 'gracieusement.'] },
  { id: 167, level: 'C', correctRow: ['Les', 'étoiles', 'qui', 'brillent', 'la', 'nuit', 'guident', 'les', 'marins.'], incorrectRow: ['Le', 'étoile', 'qui', 'brille', 'les', 'nuits', 'guide', 'le', 'marin.'] },
  { id: 168, level: 'C', correctRow: ['Mon', 'père', 'qui', 'travaille', 'dur', 'rentre', 'tard', 'le', 'soir.'], incorrectRow: ['Mes', 'pères', 'qui', 'travaille', 'dur', 'rentre', 'tard', 'les', 'soirs.'] },
  { id: 169, level: 'C', correctRow: ['Les', 'oiseaux', 'qui', 'migrent', 'en', 'hiver', 'reviennent', 'au', 'printemps.'], incorrectRow: ['Le', 'oiseau', 'qui', 'migre', 'en', 'hiver', 'revient', 'aux', 'printemps.'] },
  { id: 170, level: 'C', correctRow: ['La', 'maîtresse', 'qui', 'enseigne', 'les', 'maths', 'explique', 'très', 'bien.'], incorrectRow: ['Les', 'maîtresses', 'qui', 'enseigne', 'la', 'math', 'explique', 'très', 'bien.'] },
  { id: 171, level: 'C', correctRow: ['Les', 'poissons', 'qui', 'nagent', 'en', 'banc', 'échappent', 'aux', 'prédateurs.'], incorrectRow: ['Le', 'poisson', 'qui', 'nage', 'en', 'bancs', 'échappe', 'au', 'prédateur.'] },
  { id: 172, level: 'C', correctRow: ['Mon', 'grand-père', 'qui', 'raconte', 'des', 'histoires', 'captive', 'son', 'auditoire.'], incorrectRow: ['Mes', 'grand-pères', 'qui', 'raconte', 'de', "l'histoire", 'captive', 'ses', 'auditoires.'] },
  { id: 173, level: 'C', correctRow: ['Les', 'fruits', 'qui', 'mûrissent', 'en', 'été', 'sont', 'délicieux.'], incorrectRow: ['Le', 'fruit', 'qui', 'mûrit', 'en', 'étés', 'est', 'délicieux.'] },
  { id: 174, level: 'C', correctRow: ['La', 'chanteuse', 'qui', 'interprète', 'cette', 'chanson', 'possède', 'une', 'belle', 'voix.'], incorrectRow: ['Les', 'chanteuses', 'qui', 'interprète', 'ces', 'chanson', 'possède', 'de', 'belles', 'voix.'] },
  { id: 175, level: 'C', correctRow: ['Les', 'arbres', 'qui', 'perdent', 'leurs', 'feuilles', 'refleurissent', 'au', 'printemps.'], incorrectRow: ['Le', 'arbre', 'qui', 'perd', 'leur', 'feuille', 'refleurit', 'aux', 'printemps.'] },
  { id: 176, level: 'C', correctRow: ['Mon', 'oncle', 'qui', 'conduit', 'des', 'camions', 'parcourt', 'tout', 'le', 'pays.'], incorrectRow: ['Mes', 'oncles', 'qui', 'conduit', 'de', 'camion', 'parcourt', 'tout', 'les', 'pays.'] },
  { id: 177, level: 'C', correctRow: ['Les', 'sorcières', 'qui', 'volent', 'sur', 'des', 'balais', 'terrifient', 'les', 'villages.'], incorrectRow: ['La', 'sorcière', 'qui', 'vole', 'sur', 'un', 'balai', 'terrifie', 'le', 'village.'] },
  { id: 178, level: 'C', correctRow: ['La', 'chanson', 'qui', 'passe', 'à', 'la', 'radio', 'plaît', 'à', 'tout', 'le', 'monde.'], incorrectRow: ['Les', 'chansons', 'qui', 'passe', 'à', 'les', 'radios', 'plaît', 'à', 'tout', 'le', 'monde.'] },
  { id: 179, level: 'C', correctRow: ['Les', 'dragons', 'qui', 'crachent', 'du', 'feu', 'effraient', 'les', 'chevaliers.'], incorrectRow: ['Le', 'dragon', 'qui', 'crache', 'des', 'feux', 'effraie', 'le', 'chevalier.'] },
  { id: 180, level: 'C', correctRow: ['Mon', 'amie', 'qui', 'adore', 'les', 'animaux', 'veut', 'devenir', 'vétérinaire.'], incorrectRow: ['Mes', 'amies', 'qui', 'adore', 'un', 'animal', 'veut', 'devenir', 'vétérinaires.'] },
  { id: 181, level: 'C', correctRow: ['Les', 'pirates', 'qui', 'naviguent', 'sur', 'les', 'mers', 'cherchent', 'des', 'trésors.'], incorrectRow: ['Le', 'pirate', 'qui', 'navigue', 'sur', 'la', 'mer', 'cherche', 'un', 'trésor.'] },
  { id: 182, level: 'C', correctRow: ['La', 'rivière', 'qui', 'coule', 'près', 'du', 'village', 'nourrit', 'la', 'terre.'], incorrectRow: ['Les', 'rivières', 'qui', 'coule', 'près', 'des', 'villages', 'nourrit', 'les', 'terres.'] },
  { id: 183, level: 'C', correctRow: ['Les', 'sportifs', 'qui', "s'entraînent", 'dur', 'gagnent', 'les', 'compétitions.'], incorrectRow: ['Le', 'sportif', 'qui', "s'entraîne", 'dur', 'gagne', 'la', 'compétition.'] },
  { id: 184, level: 'C', correctRow: ['Mon', 'professeur', 'qui', 'aime', 'son', 'métier', 'inspire', 'ses', 'élèves.'], incorrectRow: ['Mes', 'professeurs', 'qui', 'aime', 'leur', 'métier', 'inspire', 'son', 'élève.'] },
  { id: 185, level: 'C', correctRow: ['Les', 'baleines', 'qui', 'vivent', 'dans', "l'océan", 'sont', 'majestueuses.'], incorrectRow: ['La', 'baleine', 'qui', 'vis', 'dans', 'les', 'océans', 'est', 'majestueux.'] },
  { id: 186, level: 'C', correctRow: ['La', 'tour', 'qui', 'domine', 'la', 'ville', 'attire', 'les', 'touristes.'], incorrectRow: ['Les', 'tours', 'qui', 'domine', 'les', 'villes', 'attire', 'le', 'touriste.'] },
  { id: 187, level: 'C', correctRow: ['Les', 'dessins', 'qui', 'ornent', 'les', 'murs', 'racontent', 'des', 'histoires.'], incorrectRow: ['Le', 'dessin', 'qui', 'orne', 'le', 'mur', 'raconte', 'une', 'histoire.'] },
  { id: 188, level: 'C', correctRow: ['Mon', 'voisin', 'qui', 'cultive', 'son', 'jardin', 'récolte', 'de', 'beaux', 'légumes.'], incorrectRow: ['Mes', 'voisins', 'qui', 'cultive', 'leur', 'jardin', 'récolte', 'un', 'beau', 'légume.'] },
  { id: 189, level: 'C', correctRow: ['Les', 'éclairs', 'qui', 'illuminent', 'le', 'ciel', 'précèdent', 'le', 'tonnerre.'], incorrectRow: ['Le', 'éclair', 'qui', 'illumine', 'les', 'ciels', 'précède', 'les', 'tonnerres.'] },
  { id: 190, level: 'C', correctRow: ['La', 'lionne', 'qui', 'chasse', 'dans', 'la', 'savane', 'nourrit', 'ses', 'petits.'], incorrectRow: ['Les', 'lionnes', 'qui', 'chasse', 'dans', 'les', 'savanes', 'nourrit', 'son', 'petit.'] },
  { id: 191, level: 'C', correctRow: ['Les', 'robots', 'qui', 'travaillent', 'dans', "l'usine", 'remplacent', 'les', 'ouvriers.'], incorrectRow: ['Le', 'robot', 'qui', 'travaille', 'dans', 'les', 'usines', 'remplace', "l'ouvrier."] },
  { id: 192, level: 'C', correctRow: ['Mon', 'dentiste', 'qui', 'soigne', 'mes', 'dents', 'travaille', 'avec', 'douceur.'], incorrectRow: ['Mes', 'dentistes', 'qui', 'soigne', 'ma', 'dent', 'travaille', 'avec', 'douceur.'] },
  { id: 193, level: 'C', correctRow: ['Les', 'papillons', 'qui', 'butinent', 'les', 'fleurs', 'transportent', 'le', 'pollen.'], incorrectRow: ['Le', 'papillon', 'qui', 'butine', 'la', 'fleur', 'transporte', 'les', 'pollens.'] },
  { id: 194, level: 'C', correctRow: ['La', 'cloche', 'qui', 'sonne', 'chaque', 'heure', 'rythme', 'la', 'journée.'], incorrectRow: ['Les', 'cloches', 'qui', 'sonne', 'chaque', 'heures', 'rythme', 'les', 'journées.'] },
  { id: 195, level: 'C', correctRow: ['Les', 'acteurs', 'qui', 'jouent', 'cette', 'pièce', 'reçoivent', 'des', 'applaudissements.'], incorrectRow: ['Le', 'acteur', 'qui', 'joue', 'ces', 'pièces', 'reçoit', 'un', 'applaudissement.'] },
  { id: 196, level: 'C', correctRow: ['Mon', 'cheval', 'qui', 'galope', 'dans', 'le', 'pré', 'hennit', 'joyeusement.'], incorrectRow: ['Mes', 'chevaux', 'qui', 'galope', 'dans', 'les', 'prés', 'hennit', 'joyeusement.'] },
  { id: 197, level: 'C', correctRow: ['Les', 'navires', 'qui', 'traversent', "l'océan", 'affrontent', 'les', 'tempêtes.'], incorrectRow: ['Le', 'navire', 'qui', 'traverse', 'les', 'océans', 'affronte', 'la', 'tempête.'] },
  { id: 198, level: 'C', correctRow: ['La', 'bibliothèque', 'qui', 'ouvre', 'le', 'matin', 'ferme', 'le', 'soir.'], incorrectRow: ['Les', 'bibliothèques', 'qui', 'ouvre', 'les', 'matins', 'ferme', 'les', 'soirs.'] },
  { id: 199, level: 'C', correctRow: ['Les', 'monuments', 'qui', 'datent', 'du', 'Moyen', 'Âge', 'attirent', 'les', 'visiteurs.'], incorrectRow: ['Le', 'monument', 'qui', 'date', 'des', 'Moyen', 'Âges', 'attire', 'le', 'visiteur.'] },
  { id: 200, level: 'C', correctRow: ['Mon', 'héros', 'qui', 'sauve', 'le', 'monde', 'inspire', 'tous', 'les', 'enfants.'], incorrectRow: ['Mes', 'héros', 'qui', 'sauve', 'les', 'mondes', 'inspire', 'tout', 'le', 'enfant.'] },

  // 201-250: Phrases avec conjonctions de coordination
  { id: 201, level: 'C', correctRow: ['Les', 'garçons', 'jouent', 'au', 'ballon', 'et', 'les', 'filles', 'dessinent.'], incorrectRow: ['Le', 'garçon', 'joue', 'aux', 'ballons', 'et', 'la', 'fille', 'dessine.'] },
  { id: 202, level: 'C', correctRow: ['Mon', 'chat', 'dort', 'sur', 'le', 'canapé', 'mais', 'mon', 'chien', 'court', 'dehors.'], incorrectRow: ['Mes', 'chats', 'dort', 'sur', 'les', 'canapés', 'mais', 'mes', 'chiens', 'court', 'dehors.'] },
  { id: 203, level: 'C', correctRow: ['Les', 'fleurs', 'poussent', 'vite', 'car', 'le', 'soleil', 'brille', 'fort.'], incorrectRow: ['La', 'fleur', 'pousse', 'vite', 'car', 'les', 'soleils', 'brille', 'fort.'] },
  { id: 204, level: 'C', correctRow: ['Ma', 'sœur', 'aime', 'lire', 'et', 'mon', 'frère', 'préfère', 'jouer.'], incorrectRow: ['Mes', 'sœurs', 'aime', 'lire', 'et', 'mes', 'frères', 'préfère', 'jouer.'] },
  { id: 205, level: 'C', correctRow: ['Les', 'oiseaux', 'chantent', 'le', 'matin', 'ou', 'se', 'taisent', 'la', 'nuit.'], incorrectRow: ['Le', 'oiseau', 'chante', 'les', 'matins', 'ou', 'se', 'tait', 'les', 'nuits.'] },
  { id: 206, level: 'C', correctRow: ['Le', 'vent', 'souffle', 'fort', 'donc', 'les', 'arbres', 'plient.'], incorrectRow: ['Les', 'vents', 'souffle', 'fort', 'donc', 'le', 'arbre', 'plie.'] },
  { id: 207, level: 'C', correctRow: ['Les', 'élèves', 'travaillent', 'dur', 'et', 'leurs', 'parents', 'sont', 'fiers.'], incorrectRow: ['Le', 'élève', 'travaille', 'dur', 'et', 'leur', 'parent', 'est', 'fier.'] },
  { id: 208, level: 'C', correctRow: ['Mon', 'père', 'cuisine', 'le', 'dîner', 'tandis', 'que', 'ma', 'mère', 'met', 'la', 'table.'], incorrectRow: ['Mes', 'pères', 'cuisine', 'les', 'dîners', 'tandis', 'que', 'mes', 'mères', 'met', 'les', 'tables.'] },
  { id: 209, level: 'C', correctRow: ['Les', 'nuages', 'cachent', 'le', 'soleil', 'mais', 'la', 'chaleur', 'reste.'], incorrectRow: ['Le', 'nuage', 'cache', 'les', 'soleils', 'mais', 'les', 'chaleurs', 'reste.'] },
  { id: 210, level: 'C', correctRow: ['La', 'pluie', 'tombe', 'doucement', 'et', 'les', 'plantes', 'en', 'profitent.'], incorrectRow: ['Les', 'pluies', 'tombe', 'doucement', 'et', 'la', 'plante', 'en', 'profite.'] },
  { id: 211, level: 'C', correctRow: ['Les', 'enfants', 'rient', 'fort', 'car', 'le', 'clown', 'fait', 'des', 'grimaces.'], incorrectRow: ['Le', 'enfant', 'ris', 'fort', 'car', 'les', 'clowns', 'fait', 'de', 'grimace.'] },
  { id: 212, level: 'C', correctRow: ['Mon', 'ami', 'viendra', 'demain', 'ou', 'il', 'restera', 'chez', 'lui.'], incorrectRow: ['Mes', 'amis', 'viendra', 'demain', 'ou', 'ils', 'restera', 'chez', 'eux.'] },
  { id: 213, level: 'C', correctRow: ['Les', 'voitures', 'roulent', 'vite', 'donc', 'les', 'piétons', 'font', 'attention.'], incorrectRow: ['La', 'voiture', 'roule', 'vite', 'donc', 'le', 'piéton', 'fait', 'attention.'] },
  { id: 214, level: 'C', correctRow: ['Ma', 'cousine', 'étudie', 'beaucoup', 'et', 'elle', 'réussit', 'ses', 'examens.'], incorrectRow: ['Mes', 'cousines', 'étudie', 'beaucoup', 'et', 'elles', 'réussit', 'son', 'examen.'] },
  { id: 215, level: 'C', correctRow: ['Les', 'lions', 'rugissent', 'fort', 'mais', 'les', 'touristes', 'restent', 'calmes.'], incorrectRow: ['Le', 'lion', 'rugit', 'fort', 'mais', 'le', 'touriste', 'reste', 'calme.'] },
  { id: 216, level: 'C', correctRow: ['Le', 'soleil', 'se', 'couche', 'et', 'les', 'étoiles', 'apparaissent', 'dans', 'le', 'ciel.'], incorrectRow: ['Les', 'soleils', 'se', 'couche', 'et', 'le', 'étoile', 'apparaît', 'dans', 'les', 'ciels.'] },
  { id: 217, level: 'C', correctRow: ['Les', 'poules', 'pondent', 'des', 'œufs', 'car', "l'éleveur", 'les', 'nourrit', 'bien.'], incorrectRow: ['La', 'poule', 'pond', 'un', 'œuf', 'car', 'les', 'éleveurs', 'la', 'nourrit', 'bien.'] },
  { id: 218, level: 'C', correctRow: ['Mon', 'oncle', 'travaille', 'tard', 'donc', 'il', 'rentre', 'fatigué.'], incorrectRow: ['Mes', 'oncles', 'travaille', 'tard', 'donc', 'ils', 'rentre', 'fatigué.'] },
  { id: 219, level: 'C', correctRow: ['Les', 'bébés', 'pleurent', 'souvent', 'et', 'les', 'parents', 'les', 'consolent.'], incorrectRow: ['Le', 'bébé', 'pleure', 'souvent', 'et', 'le', 'parent', 'le', 'console.'] },
  { id: 220, level: 'C', correctRow: ['La', 'neige', 'tombe', 'doucement', 'ou', 'la', 'pluie', 'fouette', 'les', 'vitres.'], incorrectRow: ['Les', 'neiges', 'tombe', 'doucement', 'ou', 'les', 'pluies', 'fouette', 'la', 'vitre.'] },
  { id: 221, level: 'C', correctRow: ['Les', 'chevaux', 'galopent', 'librement', 'car', 'le', 'pré', 'est', 'grand.'], incorrectRow: ['Le', 'cheval', 'galope', 'librement', 'car', 'les', 'prés', 'est', 'grands.'] },
  { id: 222, level: 'C', correctRow: ['Mon', 'professeur', 'explique', 'bien', 'donc', 'les', 'élèves', 'comprennent', 'vite.'], incorrectRow: ['Mes', 'professeurs', 'explique', 'bien', 'donc', 'le', 'élève', 'comprend', 'vite.'] },
  { id: 223, level: 'C', correctRow: ['Les', 'dauphins', 'sautent', 'joyeusement', 'et', 'les', 'spectateurs', 'applaudissent.'], incorrectRow: ['Le', 'dauphin', 'saute', 'joyeusement', 'et', 'le', 'spectateur', 'applaudit.'] },
  { id: 224, level: 'C', correctRow: ['Ma', 'grand-mère', 'tricote', 'des', 'pulls', 'tandis', 'que', 'mon', 'grand-père', 'lit.'], incorrectRow: ['Mes', 'grand-mères', 'tricote', 'un', 'pull', 'tandis', 'que', 'mes', 'grand-pères', 'lit.'] },
  { id: 225, level: 'C', correctRow: ['Les', 'fourmis', 'travaillent', 'dur', 'mais', 'les', 'cigales', 'chantent.'], incorrectRow: ['La', 'fourmi', 'travaille', 'dur', 'mais', 'la', 'cigale', 'chante.'] },
  { id: 226, level: 'C', correctRow: ['Le', 'feu', 'brûle', 'dans', 'la', 'cheminée', 'et', 'la', 'chaleur', 'réchauffe', 'la', 'maison.'], incorrectRow: ['Les', 'feux', 'brûle', 'dans', 'les', 'cheminées', 'et', 'les', 'chaleurs', 'réchauffe', 'les', 'maisons.'] },
  { id: 227, level: 'C', correctRow: ['Les', 'pirates', 'cherchent', 'le', 'trésor', 'car', 'la', 'carte', 'indique', 'sa', 'position.'], incorrectRow: ['Le', 'pirate', 'cherche', 'les', 'trésors', 'car', 'les', 'cartes', 'indique', 'leur', 'position.'] },
  { id: 228, level: 'C', correctRow: ['Mon', 'petit', 'frère', 'grandit', 'vite', 'donc', 'ses', 'vêtements', 'deviennent', 'petits.'], incorrectRow: ['Mes', 'petits', 'frères', 'grandit', 'vite', 'donc', 'son', 'vêtement', 'devient', 'petit.'] },
  { id: 229, level: 'C', correctRow: ['Les', 'abeilles', 'butinent', 'les', 'fleurs', 'et', 'elles', 'fabriquent', 'du', 'miel.'], incorrectRow: ['Le', 'abeille', 'butine', 'la', 'fleur', 'et', 'elle', 'fabrique', 'des', 'miels.'] },
  { id: 230, level: 'C', correctRow: ['La', 'lune', 'brille', 'la', 'nuit', 'ou', 'les', 'nuages', 'la', 'cachent.'], incorrectRow: ['Les', 'lunes', 'brille', 'les', 'nuits', 'ou', 'le', 'nuage', 'les', 'cache.'] },
  { id: 231, level: 'C', correctRow: ['Les', 'enfants', 'adorent', 'les', 'bonbons', 'mais', 'ils', 'mangent', 'des', 'fruits.'], incorrectRow: ['Le', 'enfant', 'adore', 'le', 'bonbon', 'mais', 'il', 'mange', 'un', 'fruit.'] },
  { id: 232, level: 'C', correctRow: ['Mon', 'voisin', 'tond', 'sa', 'pelouse', 'et', 'il', 'arrose', 'ses', 'fleurs.'], incorrectRow: ['Mes', 'voisins', 'tond', 'leur', 'pelouse', 'et', 'ils', 'arrose', 'son', 'fleur.'] },
  { id: 233, level: 'C', correctRow: ['Les', 'trains', 'arrivent', 'à', "l'heure", 'donc', 'les', 'voyageurs', 'sont', 'contents.'], incorrectRow: ['Le', 'train', 'arrive', 'aux', 'heures', 'donc', 'le', 'voyageur', 'est', 'content.'] },
  { id: 234, level: 'C', correctRow: ['Ma', 'tante', 'cuisine', 'des', 'gâteaux', 'car', 'elle', 'reçoit', 'des', 'invités.'], incorrectRow: ['Mes', 'tantes', 'cuisine', 'un', 'gâteau', 'car', 'elles', 'reçoit', 'un', 'invité.'] },
  { id: 235, level: 'C', correctRow: ['Les', 'étoiles', 'filantes', 'traversent', 'le', 'ciel', 'et', 'les', 'enfants', 'font', 'des', 'vœux.'], incorrectRow: ['Le', 'étoile', 'filante', 'traverse', 'les', 'ciels', 'et', 'le', 'enfant', 'fait', 'un', 'vœu.'] },
  { id: 236, level: 'C', correctRow: ['Le', 'jardinier', 'plante', 'des', 'fleurs', 'tandis', 'que', 'son', 'assistant', 'arrose.'], incorrectRow: ['Les', 'jardiniers', 'plante', 'une', 'fleur', 'tandis', 'que', 'ses', 'assistants', 'arrose.'] },
  { id: 237, level: 'C', correctRow: ['Les', 'loups', 'hurlent', 'dans', 'la', 'forêt', 'mais', 'personne', 'ne', 'les', 'entend.'], incorrectRow: ['Le', 'loup', 'hurle', 'dans', 'les', 'forêts', 'mais', 'personne', 'ne', 'le', 'entend.'] },
  { id: 238, level: 'C', correctRow: ['Mon', 'chat', 'attrape', 'des', 'souris', 'car', 'il', 'est', 'un', 'bon', 'chasseur.'], incorrectRow: ['Mes', 'chats', 'attrape', 'une', 'souris', 'car', 'ils', 'est', 'de', 'bons', 'chasseurs.'] },
  { id: 239, level: 'C', correctRow: ['Les', 'voitures', 'électriques', 'protègent', "l'environnement", 'donc', 'elles', 'deviennent', 'populaires.'], incorrectRow: ['La', 'voiture', 'électrique', 'protège', 'les', 'environnements', 'donc', 'elle', 'devient', 'populaire.'] },
  { id: 240, level: 'C', correctRow: ['Ma', 'mère', 'travaille', 'le', 'jour', 'et', 'elle', 'se', 'repose', 'le', 'soir.'], incorrectRow: ['Mes', 'mères', 'travaille', 'les', 'jours', 'et', 'elles', 'se', 'repose', 'les', 'soirs.'] },
  { id: 241, level: 'C', correctRow: ['Les', 'tournesols', 'suivent', 'le', 'soleil', 'car', 'ils', 'cherchent', 'la', 'lumière.'], incorrectRow: ['Le', 'tournesol', 'suit', 'les', 'soleils', 'car', 'il', 'cherche', 'les', 'lumières.'] },
  { id: 242, level: 'C', correctRow: ['Le', 'pompier', 'éteint', 'les', 'feux', 'donc', 'il', 'sauve', 'des', 'vies.'], incorrectRow: ['Les', 'pompiers', 'éteint', 'le', 'feu', 'donc', 'ils', 'sauve', 'une', 'vie.'] },
  { id: 243, level: 'C', correctRow: ['Les', 'papillons', 'colorés', 'volent', 'dans', 'le', 'jardin', 'et', 'ils', 'butinent', 'les', 'fleurs.'], incorrectRow: ['Le', 'papillon', 'coloré', 'vole', 'dans', 'les', 'jardins', 'et', 'il', 'butine', 'la', 'fleur.'] },
  { id: 244, level: 'C', correctRow: ['Mon', 'dentiste', 'soigne', 'mes', 'dents', 'tandis', 'que', "l'assistante", 'prépare', 'les', 'outils.'], incorrectRow: ['Mes', 'dentistes', 'soigne', 'ma', 'dent', 'tandis', 'que', 'les', 'assistantes', 'prépare', "l'outil."] },
  { id: 245, level: 'C', correctRow: ['Les', 'pirates', 'naviguent', 'sur', 'les', 'mers', 'mais', 'la', 'marine', 'les', 'poursuit.'], incorrectRow: ['Le', 'pirate', 'navigue', 'sur', 'la', 'mer', 'mais', 'les', 'marines', 'le', 'poursuit.'] },
  { id: 246, level: 'C', correctRow: ['La', 'rivière', 'coule', 'doucement', 'et', 'les', 'poissons', 'y', 'nagent.'], incorrectRow: ['Les', 'rivières', 'coule', 'doucement', 'et', 'le', 'poisson', 'y', 'nage.'] },
  { id: 247, level: 'C', correctRow: ['Les', 'écureuils', 'ramassent', 'des', 'noisettes', 'car', "l'hiver", 'approche.'], incorrectRow: ['Le', 'écureuil', 'ramasse', 'une', 'noisette', 'car', 'les', 'hivers', 'approche.'] },
  { id: 248, level: 'C', correctRow: ['Mon', 'frère', 'joue', 'du', 'piano', 'donc', 'il', 'prend', 'des', 'cours.'], incorrectRow: ['Mes', 'frères', 'joue', 'des', 'pianos', 'donc', 'ils', 'prend', 'un', 'cours.'] },
  { id: 249, level: 'C', correctRow: ['Les', 'nuages', 'noirs', 'arrivent', 'vite', 'et', "l'orage", 'éclate', 'bientôt.'], incorrectRow: ['Le', 'nuage', 'noir', 'arrive', 'vite', 'et', 'les', 'orages', 'éclate', 'bientôt.'] },
  { id: 250, level: 'C', correctRow: ['Ma', 'sœur', 'lit', 'des', 'romans', 'tandis', 'que', 'je', 'regarde', 'la', 'télévision.'], incorrectRow: ['Mes', 'sœurs', 'lit', 'un', 'roman', 'tandis', 'que', 'je', 'regarde', 'les', 'télévisions.'] },

  // 251-300: Phrases avec propositions subordonnées variées
  { id: 251, level: 'C', correctRow: ['Quand', 'les', 'enfants', 'arrivent', 'à', "l'école,", 'ils', 'rangent', 'leurs', 'affaires.'], incorrectRow: ['Quand', 'le', 'enfant', 'arrive', 'aux', 'écoles,', 'il', 'range', 'son', 'affaire.'] },
  { id: 252, level: 'C', correctRow: ['Si', 'ma', 'sœur', 'étudie', 'bien,', 'elle', 'réussira', 'son', 'examen.'], incorrectRow: ['Si', 'mes', 'sœurs', 'étudie', 'bien,', 'elles', 'réussira', 'leur', 'examen.'] },
  { id: 253, level: 'C', correctRow: ['Pendant', 'que', 'les', 'oiseaux', 'chantent,', 'le', 'soleil', 'se', 'lève', 'doucement.'], incorrectRow: ['Pendant', 'que', 'le', 'oiseau', 'chante,', 'les', 'soleils', 'se', 'lève', 'doucement.'] },
  { id: 254, level: 'C', correctRow: ['Lorsque', 'mon', 'père', 'rentre', 'tard,', 'il', 'dîne', 'seul.'], incorrectRow: ['Lorsque', 'mes', 'pères', 'rentre', 'tard,', 'ils', 'dîne', 'seul.'] },
  { id: 255, level: 'C', correctRow: ['Parce', 'que', 'les', 'fleurs', 'fanent,', 'le', 'jardinier', 'les', 'arrose', 'souvent.'], incorrectRow: ['Parce', 'que', 'la', 'fleur', 'fane,', 'les', 'jardiniers', 'la', 'arrose', 'souvent.'] },
  { id: 256, level: 'C', correctRow: ['Bien', 'que', 'la', 'nuit', 'tombe,', 'les', 'enfants', 'jouent', 'encore', 'dehors.'], incorrectRow: ['Bien', 'que', 'les', 'nuits', 'tombe,', 'le', 'enfant', 'joue', 'encore', 'dehors.'] },
  { id: 257, level: 'C', correctRow: ['Dès', 'que', 'les', 'invités', 'arrivent,', 'mon', 'oncle', 'ouvre', 'la', 'porte.'], incorrectRow: ['Dès', 'que', 'le', 'invité', 'arrive,', 'mes', 'oncles', 'ouvre', 'les', 'portes.'] },
  { id: 258, level: 'C', correctRow: ['Puisque', 'les', 'lions', 'dorment,', 'les', 'touristes', 'peuvent', 'approcher.'], incorrectRow: ['Puisque', 'le', 'lion', 'dors', 'les', 'touriste', 'peut', 'approcher.'] },
  { id: 259, level: 'C', correctRow: ['Aussitôt', 'que', 'ma', 'mère', 'appelle,', 'je', 'descends', 'rapidement.'], incorrectRow: ['Aussitôt', 'que', 'mes', 'mères', 'appelle,', 'je', 'descends', 'rapidement.'] },
  { id: 260, level: 'C', correctRow: ['Tandis', 'que', 'les', 'chats', 'chassent,', 'les', 'souris', 'se', 'cachent.'], incorrectRow: ['Tandis', 'que', 'le', 'chat', 'chasse,', 'la', 'souris', 'se', 'cache.'] },
  { id: 261, level: 'C', correctRow: ['Avant', 'que', 'le', 'jour', 'se', 'lève,', 'les', 'coqs', 'chantent', 'déjà.'], incorrectRow: ['Avant', 'que', 'les', 'jours', 'se', 'lève,', 'le', 'coq', 'chante', 'déjà.'] },
  { id: 262, level: 'C', correctRow: ['Après', 'que', 'les', 'élèves', 'ont', 'fini,', 'le', 'professeur', 'corrige', 'les', 'copies.'], incorrectRow: ['Après', 'que', 'le', 'élève', 'a', 'fini,', 'les', 'professeurs', 'corrige', 'la', 'copie.'] },
  { id: 263, level: 'C', correctRow: ['Même', 'si', 'ma', 'sœur', 'est', 'fatiguée,', 'elle', 'termine', 'ses', 'devoirs.'], incorrectRow: ['Même', 'si', 'mes', 'sœurs', 'est', 'fatiguée,', 'elles', 'termine', 'leur', 'devoir.'] },
  { id: 264, level: 'C', correctRow: ['Comme', 'les', 'nuages', 'arrivent,', 'la', 'pluie', 'va', 'tomber', 'bientôt.'], incorrectRow: ['Comme', 'le', 'nuage', 'arrive,', 'les', 'pluies', 'va', 'tomber', 'bientôt.'] },
  { id: 265, level: 'C', correctRow: ['Quoique', 'le', 'vent', 'soit', 'fort,', 'les', 'voiliers', 'naviguent', 'encore.'], incorrectRow: ['Quoique', 'les', 'vents', 'soit', 'fort,', 'le', 'voilier', 'navigue', 'encore.'] },
  { id: 266, level: 'C', correctRow: ['Pendant', 'que', 'mon', 'frère', 'dort,', 'je', 'lis', 'tranquillement.'], incorrectRow: ['Pendant', 'que', 'mes', 'frères', 'dort,', 'je', 'lis', 'tranquillement.'] },
  { id: 267, level: 'C', correctRow: ['Quand', 'les', 'feuilles', 'tombent,', "l'automne", 's\'installe', 'vraiment.'], incorrectRow: ['Quand', 'la', 'feuille', 'tombe,', 'les', 'automnes', 's\'installe', 'vraiment.'] },
  { id: 268, level: 'C', correctRow: ['Si', 'les', 'poules', 'pondent', 'bien,', "l'éleveur", 'sera', 'content.'], incorrectRow: ['Si', 'la', 'poule', 'pond', 'bien,', 'les', 'éleveurs', 'sera', 'contents.'] },
  { id: 269, level: 'C', correctRow: ['Lorsque', 'ma', 'tante', 'cuisine,', 'toute', 'la', 'maison', 'sent', 'bon.'], incorrectRow: ['Lorsque', 'mes', 'tantes', 'cuisine,', 'toutes', 'les', 'maisons', 'sent', 'bon.'] },
  { id: 270, level: 'C', correctRow: ['Parce', 'que', 'les', 'routes', 'sont', 'glissantes,', 'les', 'voitures', 'roulent', 'doucement.'], incorrectRow: ['Parce', 'que', 'la', 'route', 'est', 'glissante,', 'la', 'voiture', 'roule', 'doucement.'] },
  { id: 271, level: 'C', correctRow: ['Bien', 'que', 'le', 'film', 'soit', 'long,', 'les', 'enfants', 'restent', 'attentifs.'], incorrectRow: ['Bien', 'que', 'les', 'films', 'soit', 'long,', 'le', 'enfant', 'reste', 'attentif.'] },
  { id: 272, level: 'C', correctRow: ['Dès', 'que', 'ma', 'mère', 'rentre,', 'je', 'lui', 'raconte', 'ma', 'journée.'], incorrectRow: ['Dès', 'que', 'mes', 'mères', 'rentre,', 'je', 'leur', 'raconte', 'mes', 'journées.'] },
  { id: 273, level: 'C', correctRow: ['Puisque', 'les', 'magasins', 'ferment,', 'les', 'gens', 'rentrent', 'chez', 'eux.'], incorrectRow: ['Puisque', 'le', 'magasin', 'ferme,', 'le', 'gen', 'rentre', 'chez', 'lui.'] },
  { id: 274, level: 'C', correctRow: ['Aussitôt', 'que', 'le', 'professeur', 'entre,', 'les', 'élèves', 'se', 'taisent.'], incorrectRow: ['Aussitôt', 'que', 'les', 'professeurs', 'entre,', 'le', 'élève', 'se', 'tait.'] },
  { id: 275, level: 'C', correctRow: ['Tandis', 'que', 'les', 'adultes', 'travaillent,', 'les', 'enfants', 'vont', 'à', "l'école."], incorrectRow: ['Tandis', 'que', 'le', 'adulte', 'travaille,', 'le', 'enfant', 'va', 'aux', 'écoles.'] },
  { id: 276, level: 'C', correctRow: ['Avant', 'que', 'les', 'invités', 'arrivent,', 'ma', 'sœur', 'nettoie', 'la', 'maison.'], incorrectRow: ['Avant', 'que', 'le', 'invité', 'arrive,', 'mes', 'sœurs', 'nettoie', 'les', 'maisons.'] },
  { id: 277, level: 'C', correctRow: ['Après', 'que', 'le', 'spectacle', 'finit,', 'les', 'spectateurs', 'applaudissent', 'fort.'], incorrectRow: ['Après', 'que', 'les', 'spectacles', 'finit,', 'le', 'spectateur', 'applaudit', 'fort.'] },
  { id: 278, level: 'C', correctRow: ['Même', 'si', 'les', 'journées', 'sont', 'longues,', 'mon', 'père', 'reste', 'souriant.'], incorrectRow: ['Même', 'si', 'la', 'journée', 'est', 'longue,', 'mes', 'pères', 'reste', 'souriant.'] },
  { id: 279, level: 'C', correctRow: ['Comme', 'la', 'mer', 'est', 'calme,', 'les', 'bateaux', 'sortent', 'du', 'port.'], incorrectRow: ['Comme', 'les', 'mers', 'est', 'calme,', 'le', 'bateau', 'sort', 'des', 'ports.'] },
  { id: 280, level: 'C', correctRow: ['Quoique', 'les', 'exercices', 'soient', 'difficiles,', 'ma', 'sœur', 'les', 'réussit.'], incorrectRow: ['Quoique', 'le', 'exercice', 'soit', 'difficile,', 'mes', 'sœurs', 'le', 'réussit.'] },
  { id: 281, level: 'C', correctRow: ['Pendant', 'que', 'les', 'musiciens', 'jouent,', 'le', 'public', 'écoute', 'attentivement.'], incorrectRow: ['Pendant', 'que', 'le', 'musicien', 'joue,', 'les', 'publics', 'écoute', 'attentivement.'] },
  { id: 282, level: 'C', correctRow: ['Quand', 'le', 'réveil', 'sonne,', 'les', 'enfants', 'se', 'lèvent', 'péniblement.'], incorrectRow: ['Quand', 'les', 'réveils', 'sonne,', 'le', 'enfant', 'se', 'lève', 'péniblement.'] },
  { id: 283, level: 'C', correctRow: ['Si', 'les', 'plantes', 'manquent', "d'eau,", 'elles', 'flétrissent', 'rapidement.'], incorrectRow: ['Si', 'la', 'plante', 'manque', 'des', 'eaux,', 'elle', 'flétrit', 'rapidement.'] },
  { id: 284, level: 'C', correctRow: ['Lorsque', 'les', 'vacances', 'commencent,', 'toute', 'la', 'famille', 'se', 'réjouit.'], incorrectRow: ['Lorsque', 'la', 'vacance', 'commence,', 'toutes', 'les', 'familles', 'se', 'réjouit.'] },
  { id: 285, level: 'C', correctRow: ['Parce', 'que', 'mon', 'chat', 'a', 'faim,', 'il', 'miaule', 'bruyamment.'], incorrectRow: ['Parce', 'que', 'mes', 'chats', 'a', 'faim,', 'ils', 'miaule', 'bruyamment.'] },
  { id: 286, level: 'C', correctRow: ['Bien', 'que', 'les', 'montagnes', 'soient', 'hautes,', 'les', 'alpinistes', 'les', 'gravissent.'], incorrectRow: ['Bien', 'que', 'la', 'montagne', 'soit', 'haute,', 'le', 'alpiniste', 'la', 'gravit.'] },
  { id: 287, level: 'C', correctRow: ['Dès', 'que', 'les', 'oiseaux', 'chantent,', 'le', 'jour', 'se', 'lève.'], incorrectRow: ['Dès', 'que', 'le', 'oiseau', 'chante,', 'les', 'jours', 'se', 'lève.'] },
  { id: 288, level: 'C', correctRow: ['Puisque', 'ma', 'cousine', 'aime', 'danser,', 'elle', 'prend', 'des', 'cours.'], incorrectRow: ['Puisque', 'mes', 'cousines', 'aime', 'danser,', 'elles', 'prend', 'un', 'cours.'] },
  { id: 289, level: 'C', correctRow: ['Aussitôt', 'que', 'les', 'lumières', "s'éteignent,", 'le', 'spectacle', 'commence.'], incorrectRow: ['Aussitôt', 'que', 'la', 'lumière', "s'éteint,", 'les', 'spectacles', 'commence.'] },
  { id: 290, level: 'C', correctRow: ['Tandis', 'que', 'le', 'bébé', 'dort,', 'les', 'parents', 'se', 'reposent.'], incorrectRow: ['Tandis', 'que', 'les', 'bébés', 'dort,', 'le', 'parent', 'se', 'repose.'] },
  { id: 291, level: 'C', correctRow: ['Avant', 'que', 'la', 'cloche', 'sonne,', 'les', 'élèves', 'rangent', 'leurs', 'affaires.'], incorrectRow: ['Avant', 'que', 'les', 'cloches', 'sonne,', 'le', 'élève', 'range', 'son', 'affaire.'] },
  { id: 292, level: 'C', correctRow: ['Après', 'que', 'les', 'fleurs', 'ont', 'fané,', 'le', 'jardinier', 'les', 'remplace.'], incorrectRow: ['Après', 'que', 'la', 'fleur', 'a', 'fané,', 'les', 'jardiniers', 'la', 'remplace.'] },
  { id: 293, level: 'C', correctRow: ['Même', 'si', 'le', 'temps', 'est', 'mauvais,', 'les', 'coureurs', 'continuent', 'la', 'course.'], incorrectRow: ['Même', 'si', 'les', 'temps', 'est', 'mauvais,', 'le', 'coureur', 'continue', 'les', 'courses.'] },
  { id: 294, level: 'C', correctRow: ['Comme', 'les', 'fruits', 'sont', 'mûrs,', 'mon', 'père', 'les', 'cueille.'], incorrectRow: ['Comme', 'le', 'fruit', 'est', 'mûr,', 'mes', 'pères', 'le', 'cueille.'] },
  { id: 295, level: 'C', correctRow: ['Quoique', 'ma', 'sœur', 'soit', 'jeune,', 'elle', 'comprend', 'beaucoup', 'de', 'choses.'], incorrectRow: ['Quoique', 'mes', 'sœurs', 'soit', 'jeune,', 'elles', 'comprend', 'beaucoup', 'de', 'chose.'] },
  { id: 296, level: 'C', correctRow: ['Pendant', 'que', 'les', 'poissons', 'nagent,', 'le', 'pêcheur', 'lance', 'sa', 'ligne.'], incorrectRow: ['Pendant', 'que', 'le', 'poisson', 'nage,', 'les', 'pêcheurs', 'lance', 'leur', 'ligne.'] },
  { id: 297, level: 'C', correctRow: ['Quand', 'les', 'étoiles', 'apparaissent,', 'la', 'nuit', 'est', 'tombée.'], incorrectRow: ['Quand', 'le', 'étoile', 'apparaît,', 'les', 'nuits', 'est', 'tombée.'] },
  { id: 298, level: 'C', correctRow: ['Si', 'le', 'lion', 'rugit,', 'tous', 'les', 'animaux', 'se', 'cachent.'], incorrectRow: ['Si', 'les', 'lions', 'rugit,', 'tout', 'le', 'animal', 'se', 'cache.'] },
  { id: 299, level: 'C', correctRow: ['Lorsque', 'les', 'cloches', 'sonnent,', "l'église", 'se', 'remplit', 'de', 'fidèles.'], incorrectRow: ['Lorsque', 'la', 'cloche', 'sonne,', 'les', 'églises', 'se', 'remplit', 'de', 'fidèle.'] },
  { id: 300, level: 'C', correctRow: ['Parce', 'que', 'les', 'trains', 'sont', 'en', 'retard,', 'les', 'voyageurs', "s'impatientent."], incorrectRow: ['Parce', 'que', 'le', 'train', 'est', 'en', 'retards,', 'le', 'voyageur', "s'impatiente."] },
];
