'use client';

import { useState, type ReactNode } from 'react';
import { Choice, SpeakButton, useRoundFeedback } from './shared';
import type { RoundProps } from './types';
import { agreements, chronologies, detectives, isChronological, messages, moveEvent, pronouns, proofs, repairMessage } from '@/lib/progressive/french-data';

function Prompt({ text }: { text: string }) {
  return <div className="space-y-3 text-center"><h2 className="text-2xl font-bold">{text}</h2><SpeakButton text={text} /></div>;
}
function TextCard({ children }: { children: ReactNode }) {
  return <div className="space-y-3 rounded-2xl border border-sky-200 bg-sky-50 p-5 text-xl leading-relaxed text-slate-900">{children}</div>;
}
function Justification({ value, onChange }: { value: string; onChange: (s: string) => void }) {
  return <label className="block space-y-2 font-semibold">Ma justification, si je souhaite l’écrire<textarea maxLength={600} value={value} onChange={e => onChange(e.target.value)} rows={3} className="w-full rounded-xl border-2 bg-background p-3 text-lg font-normal focus-visible:ring-4 focus-visible:ring-primary/40" placeholder="Je le sais parce que…" /><span className="block text-sm font-normal text-muted-foreground">Ce texte sera conservé pour être relu avec l’enseignant.</span></label>;
}
function SentenceText({ sentences, selected, disabled, onSelect, label }: { sentences: string[]; selected: number | number[] | null; disabled?: boolean; onSelect: (index: number) => void; label: string }) {
  return <TextCard><div className="leading-[2.5]" role="group" aria-label={label}>{sentences.map((sentence, index) => { const pressed = Array.isArray(selected) ? selected.includes(index) : selected === index; return <button key={sentence} type="button" disabled={disabled} aria-pressed={pressed} onClick={() => onSelect(index)} className={`mr-1 inline min-h-12 rounded-lg border-2 px-2 py-2 text-left align-baseline font-medium transition focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-sky-400 ${pressed ? 'border-amber-500 bg-yellow-200' : 'border-transparent hover:border-sky-300 hover:bg-white'} disabled:opacity-100`}>{sentence}</button>; })}</div></TextCard>;
}

export function FrenchRound({ slug, round, onComplete }: RoundProps & { slug: string }) {
  const feedback = useRoundFeedback(onComplete);
  const [step, setStep] = useState(0);
  const [selected, setSelected] = useState<number | null>(null);
  const [answer, setAnswer] = useState('');
  const [selectedEvidence, setSelectedEvidence] = useState<number[]>([]);
  const [tool, setTool] = useState<'capital' | 'period'>('capital');
  const [capital, setCapital] = useState<number | null>(null);
  const [period, setPeriod] = useState<number | null>(null);
  const [edits, setEdits] = useState<Record<number, string>>({});
  const [order, setOrder] = useState([2, 0, 3, 1]);
  const [justification, setJustification] = useState('');
  let content: ReactNode;

  if (slug === 'detective-phrase') {
    const q = detectives[round % detectives.length];
    content = <><Prompt text="Touche dans le texte la phrase qui permet de vérifier l’affirmation." /><p className="rounded-xl bg-amber-50 p-4 text-xl font-bold">Affirmation : « {q.assertion} »</p><SentenceText sentences={q.sentences} selected={selected} disabled={step > 0} label="Texte de l’enquête" onSelect={index => feedback.check(String(index), String(q.evidence), () => { setSelected(index); setStep(1); })} />{step === 1 && <div className="space-y-4"><p className="text-center text-xl">La phrase surlignée…</p><div className="grid gap-3 sm:grid-cols-2">{[[true, 'prouve l’affirmation'], [false, 'contredit l’affirmation']].map(([value, label]) => <Choice key={String(value)} onClick={() => feedback.check(String(value), String(q.truth), () => feedback.finish(`${q.sentences[q.evidence]} — ${label}`, `${q.sentences[q.evidence]} — ${q.truth ? 'prouve' : 'contredit'}`))}>{label}</Choice>)}</div></div>}</>;
  } else if (slug === 'reparer-message') {
    const sentence = messages[round % messages.length]; const words = sentence.split(' ');
    const repaired = repairMessage(sentence, capital, period); const correct = repairMessage(sentence, 0, words.length - 1);
    content = <><Prompt text="Place la majuscule et le point pour réparer le message." />{step === 0 ? <><div className="flex flex-wrap justify-center gap-3"><Choice selected={tool === 'capital'} onClick={() => setTool('capital')}>Outil majuscule</Choice><Choice selected={tool === 'period'} onClick={() => setTool('period')}>Outil point</Choice></div><p className="text-center">{tool === 'capital' ? 'Touche un mot pour placer ou retirer la majuscule.' : 'Touche un mot pour placer ou retirer le point après lui.'}</p><TextCard><div className="text-center leading-[2.7]" role="group" aria-label="Phrase à réparer">{words.map((word, index) => <button type="button" key={index} aria-pressed={capital === index || period === index} onClick={() => tool === 'capital' ? setCapital(value => value === index ? null : index) : setPeriod(value => value === index ? null : index)} className={`inline min-h-12 rounded-md px-1.5 focus-visible:ring-4 focus-visible:ring-sky-400 ${capital === index || period === index ? 'bg-yellow-200 ring-2 ring-amber-500' : 'hover:bg-white'}`}>{capital === index ? word[0].toUpperCase() + word.slice(1) : word}{period === index ? <strong className="text-sky-700">.</strong> : ''}<span aria-hidden="true"> </span></button>)}</div></TextCard><div className="text-center"><Choice disabled={capital === null || period === null} onClick={() => feedback.check(repaired, correct, () => setStep(1))}>Vérifier la phrase</Choice></div></> : <div className="space-y-5 text-center"><TextCard><p className="font-bold text-emerald-800">{correct}</p></TextCard><p>La majuscule ouvre la phrase et le point la termine.</p><SpeakButton text={correct} /><Choice onClick={() => feedback.finish(correct, correct)}>J’ai lu la phrase</Choice></div>}</>;
  } else if (slug === 'accord-reparer') {
    const q = agreements[round % agreements.length]; const values = q.words.map((word, index) => edits[index] ?? word.initial); const expected = q.words.map(word => word.correct).join(' ');
    content = <><Prompt text="Vérifie chaque mot et accorde le groupe nominal." /><TextCard><div className="flex flex-wrap items-end gap-2">{q.words.map((word, index) => <span key={index} className="flex flex-col items-center gap-1"><small className="text-xs font-semibold text-slate-600">{word.role}</small><Choice disabled={step > 0} selected={selected === index} onClick={() => setSelected(index)}>{values[index]}</Choice>{step > 0 && <span className="text-sm font-bold text-emerald-700" aria-label={`${word.role} correctement accordé`}>✓ {word.correct}</span>}</span>)}<span className="pb-3">{q.ending}</span></div></TextCard>{step === 0 && <>{selected !== null && <div className="space-y-3"><p className="text-center">Choisis la forme du {q.words[selected].role.toLowerCase()}.</p><div className="flex flex-wrap justify-center gap-3">{q.words[selected].choices.map(value => <Choice key={value} selected={values[selected] === value} onClick={() => { setEdits(previous => ({ ...previous, [selected]: value })); setSelected(null); }}>{value}</Choice>)}</div></div>}<div className="text-center"><Choice onClick={() => feedback.check(values.join(' '), expected, () => setStep(1))}>Vérifier l’accord</Choice></div></>}{step === 1 && <div className="space-y-4 text-center"><p className="rounded-xl bg-emerald-50 p-4 text-emerald-900">{q.rule}</p><Choice onClick={() => feedback.finish(`${expected} ${q.ending}`, `${expected} ${q.ending}`)}>J’ai compris l’accord</Choice></div>}</>;
  } else if (slug === 'referent-pronom') {
    const q = pronouns[round % pronouns.length];
    content = <><Prompt text={`Touche dans le texte le nom repris par « ${q.pronoun} ».`} /><TextCard>{q.sentences.map((sentence, sentenceIndex) => <p key={sentence}>{sentence.split(new RegExp(`(${[...q.people, q.pronoun].join('|')})`, 'g')).map((part, index) => part === q.pronoun && sentenceIndex === q.pronounSentence ? <mark key={index} className="rounded bg-violet-200 px-1 font-bold text-violet-950">{part}</mark> : q.people.includes(part) ? <button type="button" key={index} disabled={step > 0} aria-pressed={step > 0 && part === q.answer && sentenceIndex === q.evidence} onClick={() => feedback.check(`${sentenceIndex}:${part}`, `${q.evidence}:${q.answer}`, () => { setSelected(index); setStep(1); })} className={`mx-1 inline min-h-12 rounded-lg border-2 px-2 font-bold focus-visible:ring-4 ${step > 0 && part === q.answer && sentenceIndex === q.evidence ? 'border-violet-600 bg-yellow-200' : 'border-sky-400 bg-white'}`}>{part}</button> : <span key={index}>{part}</span>)}</p>)}</TextCard>{step === 1 && <div className="space-y-4 text-center"><p className="rounded-xl bg-violet-50 p-4 text-violet-950"><strong>{q.pronoun} → {q.answer}</strong><br />{q.explanation}</p><Choice onClick={() => feedback.finish(`${q.pronoun} : ${q.answer}`, q.explanation)}>J’ai trouvé le référent</Choice></div>}</>;
  } else if (slug === 'preuves-texte') {
    const q = proofs[round % proofs.length];
    const evidenceText = selectedEvidence.map(index => q.sentences[index]).join(' ');
    const toggleEvidence = (index: number) => setSelectedEvidence(previous => previous.includes(index) ? previous.filter(value => value !== index) : [...previous, index].sort());
    const selectedKey = selectedEvidence.join(',');
    const evidenceIsValid = q.evidenceOptions.some(option => option.join(',') === selectedKey);
    content = <><Prompt text={step === 0 ? q.question : step === 1 ? 'Sélectionne dans le texte la ou les phrases qui justifient ta réponse.' : 'Ta réponse et tes preuves sont conservées.'} /><SentenceText sentences={q.sentences} selected={selectedEvidence} disabled={step !== 1} label="Texte à lire" onSelect={toggleEvidence} />{step === 0 && <div className="grid gap-3">{q.answers.map(value => <Choice key={value} onClick={() => feedback.check(value, q.answer, () => { setAnswer(value); setStep(1); })}>{value}</Choice>)}</div>}{step >= 1 && <p className="rounded-xl bg-sky-50 p-4"><strong>Ma réponse :</strong> {answer}</p>}{step === 1 && <div className="text-center"><Choice disabled={selectedEvidence.length === 0} onClick={() => feedback.check(selectedKey, evidenceIsValid ? selectedKey : q.evidenceOptions[0].join(','), () => setStep(2))}>Vérifier mes preuves</Choice></div>}{step === 2 && <><p className="rounded-xl bg-emerald-50 p-4"><strong>Mes preuves :</strong> « {evidenceText} »</p><Justification value={justification} onChange={setJustification} /><div className="text-center"><Choice onClick={() => feedback.finish(`${answer} ; preuves : ${evidenceText}${justification.trim() ? ` ; justification : ${justification.trim()}` : ''}`, `${q.answer} ; ${evidenceText}`)}>Terminer ma réponse</Choice></div></>}</>;
  } else {
    const q = chronologies[round % chronologies.length];
    content = <><Prompt text={step === 0 ? 'Lis le récit, puis remets les événements dans l’ordre.' : step === 1 ? q.question : step === 2 ? 'Quel lien explique la suite des événements ?' : 'Tu as retrouvé l’ordre et le lien entre les événements.'} /><TextCard><p>{q.story}</p></TextCard>{step === 0 && <><ol className="space-y-3">{order.map((event, index) => <li key={event} className="flex items-center gap-3 rounded-xl border p-3"><strong className="text-xl">{index + 1}.</strong><span className="flex-1 text-lg">{q.events[event]}</span><div className="flex gap-2 sm:flex-col"><button type="button" disabled={index === 0} aria-label={`Monter : ${q.events[event]}`} onClick={() => setOrder(previous => moveEvent(previous, index, -1))} className="min-h-12 min-w-12 rounded-lg border-2 text-xl disabled:opacity-25">↑</button><button type="button" disabled={index === 3} aria-label={`Descendre : ${q.events[event]}`} onClick={() => setOrder(previous => moveEvent(previous, index, 1))} className="min-h-12 min-w-12 rounded-lg border-2 text-xl disabled:opacity-25">↓</button></div></li>)}</ol><div className="text-center"><Choice onClick={() => feedback.check(String(isChronological(order)), 'true', () => setStep(1))}>Vérifier l’ordre</Choice></div></>}{step === 1 && <div className="grid gap-3">{[2, 0, 3, 1].map(index => <Choice key={index} onClick={() => feedback.check(String(index), String(q.cause), () => setStep(2))}>{q.events[index]}</Choice>)}</div>}{step === 2 && <div className="grid gap-3">{q.links.map(link => <Choice key={link} onClick={() => feedback.check(link, q.link, () => setStep(3))}>{link}</Choice>)}</div>}{step === 3 && <><p className="rounded-xl bg-emerald-50 p-4">{q.link}</p><Justification value={justification} onChange={setJustification} /><div className="text-center"><Choice onClick={() => feedback.finish(`${q.events.join(' → ')} ; ${q.link}${justification.trim() ? ` ; explication : ${justification.trim()}` : ''}`, `${q.events.join(' → ')} ; ${q.link}`)}>Terminer ma réponse</Choice></div></>}</>;
  }
  return <div className="space-y-6">{content}{feedback.error && <p role="alert" className="rounded-xl bg-amber-50 p-4 text-center font-semibold text-amber-900">{feedback.error}</p>}</div>;
}
