export const detectives = [
  { sentences: ['Lina prépare son sac.', 'Elle glisse un livre dans la poche bleue.', 'Son goûter reste sur la table.'], assertion: 'Le goûter est dans le sac.', truth: false, evidence: 2 },
  { sentences: ['Tom arrive au jardin.', 'Il arrose les salades avec son arrosoir.', 'Puis il range ses bottes.'], assertion: 'Tom arrose les salades.', truth: true, evidence: 1 },
  { sentences: ['Le car s’arrête devant l’école.', 'Les enfants montent avec leur maîtresse.', 'Ils vont visiter une ferme.', 'Le trajet dure vingt minutes.'], assertion: 'Les enfants vont à la piscine.', truth: false, evidence: 2 },
  { sentences: ['Mila observe le ciel.', 'De gros nuages arrivent.', 'Elle ouvre son parapluie car la pluie commence.'], assertion: 'Il pleut.', truth: true, evidence: 2 },
];
export const messages = ['le petit chat dort sur le tapis', 'nous préparons une soupe de légumes', 'une étoile brille dans le ciel', 'les enfants jouent dans la cour'];
export function repairMessage(text: string, capital: number | null, period: number | null): string {
  return text.split(' ').map((word, index) => (index === capital ? word[0].toUpperCase() + word.slice(1) : word) + (index === period ? '.' : '')).join(' ');
}
type AgreementWord = { role: string; initial: string; correct: string; choices: string[] };
function word(role: string, initial: string, correct: string, choices: string[]): AgreementWord { return { role, initial, correct, choices }; }
export const agreements = [
  { ending: 'dorment dans le panier.', rule: '« Les » annonce le pluriel : le nom et l’adjectif prennent un s.', words: [word('Déterminant', 'Les', 'Les', ['Les', 'Le']), word('Nom', 'chat', 'chats', ['chat', 'chats']), word('Adjectif', 'noir', 'noirs', ['noire', 'noirs', 'noir'])] },
  { ending: 'décorent la table.', rule: '« Des fleurs » est féminin pluriel : l’adjectif « rouges » s’accorde avec le nom.', words: [word('Déterminant', 'Des', 'Des', ['Une', 'Des']), word('Nom', 'fleurs', 'fleurs', ['fleurs', 'fleur']), word('Adjectif', 'rouge', 'rouges', ['rouge', 'rouges'])] },
  { ending: 'passe sur le pont.', rule: '« Une voiture » est féminin singulier : l’adjectif devient « verte ».', words: [word('Déterminant', 'Une', 'Une', ['Un', 'Une']), word('Nom', 'voiture', 'voiture', ['voiture', 'voitures']), word('Adjectif', 'vert', 'verte', ['vert', 'verts', 'verte'])] },
  { ending: 'sont posés près de la porte.', rule: 'Le déterminant, le nom et l’adjectif portent ensemble la marque du pluriel.', words: [word('Déterminant', 'Le', 'Les', ['Le', 'Les']), word('Nom', 'vélos', 'vélos', ['vélo', 'vélos']), word('Adjectif', 'bleu', 'bleus', ['bleus', 'bleue', 'bleu'])] },
];
export const pronouns = [
  { sentences: ['Lina apporte un livre à Tom.', 'Elle lui montre une image de dragon.', 'Tom trouve le dragon amusant.'], pronoun: 'Elle', pronounSentence: 1, people: ['Lina', 'Tom'], answer: 'Lina', evidence: 0, explanation: '« Elle » reprend Lina, le personnage féminin qui apporte le livre.' },
  { sentences: ['Hugo rejoint Inès dans la cour.', 'Il porte un ballon sous son bras.', 'Inès ouvre le portail.'], pronoun: 'Il', pronounSentence: 1, people: ['Inès', 'Hugo'], answer: 'Hugo', evidence: 0, explanation: '« Il » reprend Hugo, le personnage masculin qui rejoint Inès.' },
  { sentences: ['Léa attend son frère Noé devant la bibliothèque.', 'Elle a emprunté deux bandes dessinées.', 'Noé arrive à vélo.'], pronoun: 'Elle', pronounSentence: 1, people: ['Noé', 'Léa'], answer: 'Léa', evidence: 0, explanation: '« Elle » reprend Léa ; Noé est son frère.' },
  { sentences: ['Le jardinier Sami salue la voisine Emma.', 'Il plante ensuite un rosier.', 'Emma admire les fleurs.'], pronoun: 'Il', pronounSentence: 1, people: ['Sami', 'Emma'], answer: 'Sami', evidence: 0, explanation: '« Il » reprend Sami, le jardinier ; Emma est la voisine.' },
];
export const proofs = [
  { sentences: ['Zoé veut rentrer chez elle.', 'Au moment de partir, une forte pluie se met à tomber.', 'Elle reste sous le préau en attendant une éclaircie.', 'Son frère vient la rejoindre.'], question: 'Pourquoi Zoé reste-t-elle sous le préau ?', answers: ['Pour s’abriter de la pluie.', 'Pour attendre son frère.', 'Pour prolonger la récréation.'], answer: 'Pour s’abriter de la pluie.', evidenceOptions: [[1], [2], [1, 2]] },
  { sentences: ['Adam prépare une tarte.', 'Il ouvre le placard, puis constate qu’il n’y a plus de farine.', 'Il prend son panier et part en acheter.', 'La pâte attendra son retour.'], question: 'Pourquoi Adam sort-il faire une course ?', answers: ['Il lui manque de la farine.', 'Il veut acheter des fruits pour décorer la tarte.', 'Il va apporter la tarte à un voisin.'], answer: 'Il lui manque de la farine.', evidenceOptions: [[1], [2], [1, 2]] },
  { sentences: ['À la bibliothèque, Nour choisit un gros livre sur les oiseaux.', 'Elle veut reconnaître ceux qui viennent dans son jardin.', 'Elle emprunte le livre et le range soigneusement dans son sac.'], question: 'Dans quel but Nour choisit-elle ce livre ?', answers: ['Pour reconnaître les oiseaux de son jardin.', 'Pour apprendre à les photographier.', 'Pour savoir comment les nourrir.'], answer: 'Pour reconnaître les oiseaux de son jardin.', evidenceOptions: [[1]] },
  { sentences: ['La classe a semé des graines dans deux pots.', 'Le premier pot est arrosé chaque jour.', 'Le second ne reçoit jamais d’eau.', 'Après une semaine, seule la plante du premier pot a poussé.'], question: 'Que montre cette expérience sur le rôle de l’eau ?', answers: ['Le pot arrosé a poussé, contrairement au pot sans eau.', 'La taille des pots explique la différence.', 'Les deux pots ont poussé de la même façon.'], answer: 'Le pot arrosé a poussé, contrairement au pot sans eau.', evidenceOptions: [[1, 3], [1, 2, 3]] },
];
export const chronologies = [
  { story: 'Léo rentre avec un chapeau trempé. Un coup de vent l’avait emporté, puis il avait roulé dans une mare. Le garçon l’a récupéré avant de le laisser sécher.', narrativeOrder: [3, 0, 1, 2], events: ['Le vent emporte le chapeau.', 'Le couvre-chef tombe dans une flaque.', 'Léo récupère son chapeau mouillé.', 'Le garçon met le chapeau à sécher.'], cause: 1, question: 'Quel événement explique que le chapeau soit mouillé ?', links: ['La flaque mouille le chapeau qui y est tombé.', 'La pluie mouille le chapeau pendant le retour de Léo.', 'Léo mouille le chapeau en le lavant après l’avoir ramassé.'], link: 'La flaque mouille le chapeau qui y est tombé.' },
  { story: 'Aya entend soudain la sonnette. Elle traverse l’entrée et ouvre. Le facteur lui tend alors un paquet, qu’elle dépose ensuite sur la table.', narrativeOrder: [0, 1, 2, 3], events: ['La sonnette retentit dans la maison.', 'Aya se dirige vers la porte.', 'Le facteur donne un colis à Aya.', 'Le paquet est posé sur la table.'], cause: 0, question: 'Qu’est-ce qui pousse Aya à se déplacer vers la porte ?', links: ['Aya va à la porte parce qu’elle attend peut-être un colis.', 'La sonnerie avertit Aya que quelqu’un attend.', 'Aya se déplace parce qu’elle veut poser un paquet sur la table.'], link: 'La sonnerie avertit Aya que quelqu’un attend.' },
  { story: 'Sam peut enfin repartir après avoir gonflé son pneu. Quelques minutes plus tôt, il avait réparé la chambre à air, après avoir inspecté la roue immobilisée par une crevaison.', narrativeOrder: [3, 2, 1, 0], events: ['Le pneu du vélo se dégonfle brusquement.', 'Sam s’arrête pour observer la roue.', 'Il répare la chambre à air percée.', 'Le cycliste regonfle le pneu et repart.'], cause: 2, question: 'Quelle action permet directement de regonfler puis de repartir ?', links: ['La réparation rend la chambre à air capable de garder l’air.', 'Sam remplace la roue abîmée avant de repartir.', 'Sam change de vélo pour poursuivre son trajet.'], link: 'La réparation rend la chambre à air capable de garder l’air.' },
  { story: 'Un verre se renverse pendant le goûter. Mila part chercher une éponge, absorbe la petite mare, puis passe un torchon pour finir le nettoyage.', narrativeOrder: [0, 1, 2, 3], events: ['De l’eau se répand sur la table.', 'Mila prend une éponge.', 'L’éponge absorbe l’eau renversée.', 'Un torchon sèche la surface.'], cause: 2, question: 'Quel événement permet de retirer la plus grande partie de l’eau ?', links: ['L’éponge absorbe le liquide avant le séchage final.', 'Mila enlève l’eau avec le torchon, puis utilise l’éponge pour finir.', 'Mila recueille l’eau dans le verre avant d’essuyer la table.'], link: 'L’éponge absorbe le liquide avant le séchage final.' },
];
export function moveEvent(order: number[], index: number, direction: -1 | 1): number[] {
  const next = [...order]; const target = index + direction;
  if (index < 0 || index >= next.length || target < 0 || target >= next.length) return next;
  [next[index], next[target]] = [next[target], next[index]]; return next;
}
export function isChronological(order: number[]): boolean { return order.length === 4 && order.every((value, index) => value === index); }
